from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'diorama_environment',
        'label': 'Diorama Environment [environment] [stylized]',
        'tags': ['environment', 'stylized'],
        'description': 'Stylized diorama-environment style with miniature-stage clarity, readable composition, and contained world-building charm.',
        'instruction': 'Render as a compact diorama environment with clear scale relationships, miniature staging logic, strong silhouette grouping, and polished stylized detail. Preserve the contained self-contained feel of a display piece, with readable layers and clean focal hierarchy rather than sprawling uncontrolled environment complexity.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'environment_concept_sheet',
        'label': 'Environment Concept Sheet [environment] [concept]',
        'tags': ['environment', 'concept'],
        'description': 'Production environment-concept sheet style with layout clarity, design exploration, and readable world-building support.',
        'instruction': 'Render as a studio environment concept sheet with clean panel organization, key environment views, material or mood callouts, and production-oriented visual communication. Preserve design readability, scale cues, and coherent world-building while avoiding over-rendered final-shot polish that weakens concept-sheet utility.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'exterior_archviz',
        'label': 'Exterior Archviz [architecture] [archviz]',
        'tags': ['architecture', 'archviz'],
        'description': 'Photoreal exterior-visualization style with disciplined perspective, material realism, and presentation-ready architectural clarity.',
        'instruction': 'Render as a premium exterior architectural visualization with coherent perspective, believable scale cues, realistic facade materials, and lighting that clearly reveals structure and spatial intent. Preserve crisp line integrity, grounded landscaping, and presentation-grade polish while avoiding distorted geometry, muddy materials, or overdramatic atmosphere that weakens design readability.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'floor_plan_visualization',
        'label': 'Floor Plan Visualization [architecture] [technical]',
        'tags': ['architecture', 'technical'],
        'description': 'Floor-plan visualization style with plan-view clarity, room logic, and architectural readability.',
        'instruction': 'Render as a clean floor plan with readable walls, circulation, room hierarchy, and furniture or fixture context where useful. Preserve plan-view precision, annotation-friendly spacing, and strong architectural legibility without decorative perspective effects.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'industrial_environment_design',
        'label': 'Industrial Environment Design [environment] [industrial]',
        'tags': ['environment', 'industrial'],
        'description': 'Industrial-environment design style with functional structure, heavy material logic, and clear mechanical-spatial readability.',
        'instruction': 'Render as an industrial environment with practical construction logic, steel, concrete, pipes, ducts, grates, service lighting, and wear patterns that feel believable and usable. Preserve layout clarity, material separation, and functional spatial storytelling without turning the scene into generic sci-fi clutter or unreadable grime.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'interior_design_visualization',
        'label': 'Interior Design Visualization [interior] [archviz]',
        'tags': ['interior', 'archviz'],
        'description': 'Interior visualization style prioritizing spatial comfort, material fidelity, practical lighting mood, and livable architectural clarity.',
        'instruction': 'Render as interior design visualization with realistic scale cues, coherent furniture placement, balanced ambient and key lighting, and material textures that support a believable lived-in space. Preserve circulation, comfort, and design intent without overcrowding the room or flattening the depth.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'interior_material_board',
        'label': 'Interior Material Board [interior] [reference]',
        'tags': ['interior', 'reference'],
        'description': 'Interior-material board style with curated finish presentation, palette cohesion, and design-review clarity.',
        'instruction': 'Design as an interior material board with organized samples of finishes, textiles, woods, metals, stones, and colors in a clean presentation layout. Preserve clear comparison logic, premium board composition, and professional review readability rather than decorative collage disorder.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'interior_mood_board',
        'label': 'Interior Mood Board [interior] [design]',
        'tags': ['interior', 'design'],
        'description': 'Curated interior-design mood-board style with material cohesion, palette clarity, and presentation-friendly layout structure.',
        'instruction': 'Design as an interior mood board with coordinated materials, textiles, finishes, furniture cues, color palette swatches, and clean editorial arrangement. Preserve strong visual cohesion, luxury presentation clarity, and organized composition so the board feels like a professional design reference rather than a cluttered collage.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'landscape_architecture_visualization',
        'label': 'Landscape Architecture Visualization [landscape] [archviz]',
        'tags': ['landscape', 'archviz'],
        'description': 'Landscape-architecture visualization style focused on site planning, planted spaces, circulation, and human-scale outdoor readability.',
        'instruction': 'Render as a professional landscape-architecture visualization with clear pathways, planted zones, hardscape materials, seating areas, and strong spatial hierarchy. Preserve site-design intent, realistic vegetation placement, material distinction, and practical scale clarity while avoiding decorative clutter or overly cinematic effects that obscure functional layout.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'lighting_plan_visualization',
        'label': 'Lighting Plan Visualization [architecture] [technical]',
        'tags': ['architecture', 'technical'],
        'description': 'Lighting-plan style with fixture layout clarity, illumination zoning, and architectural systems readability.',
        'instruction': 'Render as a lighting plan with clearly marked fixture positions, lighting zones, and strong plan-view organization. Preserve technical accuracy, annotation-friendly clarity, and system readability without decorative rendering or unrelated environmental storytelling.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'room_elevation_sheet',
        'label': 'Room Elevation Sheet [interior] [technical]',
        'tags': ['interior', 'technical'],
        'description': 'Room-elevation style with wall-view accuracy, fixture placement clarity, and interior-design documentation readability.',
        'instruction': 'Render as a room elevation sheet with aligned wall views, clean orthographic structure, and readable placement of fixtures, cabinetry, openings, and finishes. Preserve technical clarity and documentation usefulness instead of atmospheric interior rendering.',
        'main_category': 'Architecture / Interior / Environment',
    },
    {
        'key': 'ruins_decayed_environment',
        'label': 'Ruins / Decayed Environment [environment] [atmospheric]',
        'tags': ['environment', 'atmospheric'],
        'description': 'Atmospheric ruined-environment style with collapse, weathering, overgrowth, and strong visual storytelling through decay.',
        'instruction': 'Render as a decayed environment with believable structural breakdown, erosion, cracked surfaces, debris, overgrowth, and light that emphasizes age and abandonment. Preserve strong composition and environmental readability while avoiding random destruction noise or excessive haze that hides the scene structure.',
        'main_category': 'Architecture / Interior / Environment',
    },
]
