from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'brand_style_guide_cover',
        'label': 'Brand Style Guide Cover [branding] [document]',
        'tags': ['branding', 'document'],
        'description': 'Brand-guideline cover style with clear identity framing, polished presentation, and corporate design-system confidence.',
        'instruction': 'Design as a brand style-guide cover with strong logo hierarchy, disciplined typography, and clean corporate presentation. Preserve brand authority, document clarity, and premium system-level polish without overcrowding the page.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'hang_tag_design',
        'label': 'Hang Tag Design [branding] [fashion]',
        'tags': ['branding', 'fashion'],
        'description': 'Fashion hang-tag style with compact hierarchy, premium brand presentation, and print-ready retail clarity.',
        'instruction': 'Design as a hang tag with clear logo hierarchy, product information zones, elegant spacing, and retail-ready print composition. Preserve brand polish and small-format readability without turning it into a cluttered mini flyer.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'logo_designer',
        'label': 'Logo Designer [branding] [vector]',
        'tags': ['branding', 'vector'],
        'description': 'Brand-first logo design style focused on simple iconic geometry, strong negative space, vector clarity, and scalable readability.',
        'instruction': 'Design as a professional logo concept with high-contrast silhouette, clean geometric balance, minimal color count, and strong mark usability across small and large sizes. Prioritize memorability, distinct shape language, and vector-friendly simplicity over illustration detail or mockup decoration.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'logo_lockup_sheet',
        'label': 'Logo Lockup Sheet [branding] [system]',
        'tags': ['branding', 'system'],
        'description': 'Logo-lockup sheet style with brand-system organization, variant consistency, and professional presentation clarity.',
        'instruction': 'Design as a logo lockup sheet showing primary, secondary, horizontal, vertical, and icon variations in a clean organized layout. Preserve spacing discipline, consistent scaling, and strong brand-system readability without unnecessary decoration.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'merch_design_graphic',
        'label': 'Merch Design Graphic [branding] [merch]',
        'tags': ['branding', 'merch'],
        'description': 'Merch-graphic style with apparel-friendly readability, bold print impact, and scalable branding clarity.',
        'instruction': 'Design as merchandise artwork for apparel or products with strong silhouette logic, print-friendly contrast, and clear visual identity. Preserve screen-print or merch usability and avoid excessive fine detail that would fail on physical products.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'minimal_graphic',
        'label': 'Minimal Graphic [design] [minimal]',
        'tags': ['design', 'minimal'],
        'description': 'Minimal design language with reduced noise, strong spacing, disciplined shape use, and clear visual hierarchy.',
        'instruction': 'Keep forms simple, spacing intentional, and color usage disciplined. Remove non-essential detail while preserving communicative impact, strong composition, and immediate readability across the whole frame.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'packaging_design',
        'label': 'Packaging Design [branding] [packaging]',
        'tags': ['branding', 'packaging'],
        'description': 'Packaging-design style with shelf readability, brand hierarchy, and commercially polished visual organization.',
        'instruction': 'Design as professional packaging with clear branding hierarchy, strong front-facing readability, disciplined typography zones, and production-aware layout logic. Keep the result retail-ready and communicative rather than decorative and cluttered.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'packaging_mock_shelf_presentation',
        'label': 'Packaging Mock Shelf Presentation [branding] [retail]',
        'tags': ['branding', 'retail'],
        'description': 'Retail packaging-presentation style with shelf context, brand block readability, and commercial display polish.',
        'instruction': 'Render as a packaging mock shelf or retail lineup with strong brand-block visibility, product differentiation, realistic packaging surfaces, and presentation-ready merchandising clarity. Preserve retail readability and shelf impact without excessive perspective chaos or clutter.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'product_advertising',
        'label': 'Product Advertising Visual [product] [commercial]',
        'tags': ['product', 'commercial'],
        'description': 'Commercial advertising style with premium staging, high-impact composition, and polished brand-ready presentation.',
        'instruction': 'Render as a premium advertising visual with intentional composition, controlled reflections, strong material appeal, and clear commercial hierarchy. Keep the product dominant, desirable, and campaign-ready without unnecessary visual clutter.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'label_design',
        'label': 'Product Label Design [design] [packaging]',
        'tags': ['design', 'packaging', 'label', 'branding'],
        'description': 'Packaging-label style with compact hierarchy, brand clarity, and production-aware product-surface readability.',
        'instruction': 'Design as a product label with clear brand hierarchy, readable small-format typography, balanced decorative restraint, and strong packaging usability. Preserve surface-fit awareness, product clarity, and shelf-readability without overcrowding the label with excessive detail.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'retail_display_stand_design',
        'label': 'Retail Display Stand Design [branding] [retail]',
        'tags': ['branding', 'retail'],
        'description': 'Retail display-stand style with product-focus hierarchy, structural presentation logic, and storefront-ready brand clarity.',
        'instruction': 'Design as a retail display stand with clear product presentation zones, brand messaging hierarchy, and believable structural layout. Preserve in-store visibility, merchandising logic, and commercial polish without collapsing into cluttered promotional overload.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'sticker_design',
        'label': 'Sticker Design [design] [branding]',
        'tags': ['design', 'branding', 'sticker', 'merch'],
        'description': 'Sticker style with bold silhouette, immediate readability, and cutout-friendly graphic clarity.',
        'instruction': 'Design as a sticker with strong silhouette impact, simplified shape logic, and clean visual hierarchy that remains readable at small size. Preserve merch-friendly appeal, bold focal design, and print/cutout practicality without excessive fine detail.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'tote_apparel_graphic_print',
        'label': 'Tote / Apparel Graphic Print [branding] [merch]',
        'tags': ['branding', 'merch'],
        'description': 'Apparel-graphic print style with bold wearable readability, strong composition, and merch-friendly print discipline.',
        'instruction': 'Design as a wearable or tote-bag graphic with high-contrast readability, print-safe composition, and strong visual identity at medium distance. Preserve merch appeal and clear graphic shape language without overcrowding the print area.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
    {
        'key': 'visual_identity_board',
        'label': 'Visual Identity Board [branding] [presentation]',
        'tags': ['branding', 'presentation'],
        'description': 'Visual-identity board style with organized brand assets, palette clarity, and polished system-presentation layout.',
        'instruction': 'Design as a visual identity board with logo treatments, palette swatches, typography samples, supporting imagery, and clear organizational hierarchy. Preserve system clarity, design cohesion, and presentation-quality spacing rather than collage-like clutter.',
        'main_category': 'Branding / Packaging / Commercial Design',
    },
]
