from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'bathroom_sink_photo_style',
        'label': 'Bathroom Sink Photo [photo] [social]',
        'tags': ['photo', 'social'],
        'description': 'Casual bathroom-sink photo style with lived-in interior realism, mirror-context framing, and social-photo authenticity.',
        'instruction': 'Render as a casual bathroom or sink-area phone photo with believable mirror or in-room framing, natural overhead or vanity lighting, realistic countertop context, and a spontaneous social-post feel. Preserve environmental realism and unforced capture quality without making the space unrealistically pristine or editorially styled.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'bedroom_mirror_photo_style',
        'label': 'Bedroom Mirror Photo [photo] [social]',
        'tags': ['photo', 'social'],
        'description': 'Bedroom-mirror photo style with personal-space realism, soft lived-in atmosphere, and casual social capture energy.',
        'instruction': 'Render as a bedroom mirror photo with realistic personal-space details, soft ambient light, casual body language, and authentic mirror composition. Preserve the intimate everyday feel of a true phone-captured image without over-staging the room or pushing the scene into glossy influencer-commercial polish.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'candid_selfie_style',
        'label': 'Candid Selfie [photo] [social]',
        'tags': ['photo', 'social'],
        'description': 'Candid selfie-photo style with unforced expression, casual composition, and naturally imperfect personal realism.',
        'instruction': 'Render as a candid selfie with relaxed expression, casual angle, everyday context, and the slightly imperfect timing of a real self-taken photo. Preserve authenticity, relatable mood, and smartphone realism rather than over-curating the shot into a polished portrait.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'car_selfie_photo_style',
        'label': 'Car Selfie Photo [photo] [mobile]',
        'tags': ['photo', 'mobile'],
        'description': 'Car-selfie photo style with vehicle-interior framing, natural window light, and realistic in-transit casual capture.',
        'instruction': 'Render as a casual car selfie or passenger-seat phone photo with believable interior framing, natural daylight spill, dashboard or window context, and smartphone-native realism. Preserve candid timing and personal-space authenticity without making it look like a staged automotive campaign.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'disposable_camera_photo_style',
        'label': 'Disposable Camera Photo [photo] [vintage]',
        'tags': ['photo', 'vintage'],
        'description': 'Disposable-camera style with flash-heavy casual realism, grain, color shift, and snapshot-era imperfection.',
        'instruction': 'Render as a disposable-camera snapshot with direct flash feel, film grain, slight color cast, modest blur or softness, and authentic point-and-shoot spontaneity. Preserve nostalgic snapshot realism without making the image too damaged or unreadable.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'flash_phone_photo_style',
        'label': 'Flash Phone Photo [photo] [mobile]',
        'tags': ['photo', 'mobile'],
        'description': 'Phone-flash photo style with direct frontal illumination, harsh close-range highlights, and nightlife or candid snapshot realism.',
        'instruction': 'Render as a smartphone flash photo with direct frontal light, harder shadows, near-camera illumination, and believable snapshot immediacy. Preserve the authentic look of a real phone flash capture without turning it into polished studio flash photography.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'friend_took_it_candid_photo',
        'label': 'Friend-Took-It Candid [photo] [candid]',
        'tags': ['photo', 'candid'],
        'description': 'Friend-shot candid-photo style with casual timing, lightly imperfect framing, and believable social realism.',
        'instruction': 'Render as a candid photo taken by a friend with natural subject behavior, imperfect but flattering composition, and real handheld timing. Preserve the feeling of a genuine in-the-moment shot instead of a posed portrait or professional session.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'group_selfie_photo_style',
        'label': 'Group Selfie Photo [photo] [social]',
        'tags': ['photo', 'social'],
        'description': "Group-selfie style with wide arm's-length composition, informal social energy, and believable smartphone distortion.",
        'instruction': 'Render as a group selfie with realistic front-camera perspective, slightly wide-angle phone behavior, uneven but natural subject spacing, and a lively shared social feel. Preserve candid energy and real group-photo imperfection without smoothing it into posed formal portraiture.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'mirror_selfie_photo',
        'label': 'Mirror Selfie Photo [photo] [social]',
        'tags': ['photo', 'social'],
        'description': 'Mirror-selfie photo style with reflected framing, visible phone presence, and social-native casual realism.',
        'instruction': 'Render as a mirror selfie with visible phone-in-hand, believable reflection geometry, casual posture, and a real room or bathroom environment. Preserve spontaneous social-photo authenticity and natural reflected light without over-staging the pose or polishing it into fashion editorial imagery.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'night_out_phone_photo',
        'label': 'Night Out Phone Photo [photo] [social]',
        'tags': ['photo', 'social'],
        'description': 'Night-out phone-photo style with party or nightlife realism, mixed practical lighting, and candid social capture energy.',
        'instruction': 'Render as a nightlife or night-out phone photo with mixed practical lights, mobile-camera exposure behavior, social spontaneity, and believable low-light smartphone realism. Preserve candid energy and atmospheric imperfection rather than cleaning it into commercial nightlife photography.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'outfit_check_mirror_photo',
        'label': 'Outfit Check Mirror Photo [photo] [social]',
        'tags': ['photo', 'social'],
        'description': 'Outfit-check mirror-photo style with full-body reflected framing, casual styling emphasis, and authentic social-post realism.',
        'instruction': 'Render as an outfit-check mirror photo with clear reflected body visibility, phone-in-hand framing, believable room context, and casual style-focused composition. Preserve social-media realism, garment readability, and natural mirror-light behavior without making it look like a studio fashion campaign.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'parking_lot_phone_photo',
        'label': 'Parking Lot Phone Photo [photo] [candid]',
        'tags': ['photo', 'candid'],
        'description': 'Casual parking-lot phone-photo style with outdoor snapshot framing, everyday realism, and unstyled social-photo authenticity.',
        'instruction': 'Render as an everyday parking-lot or sidewalk phone picture with casual handheld composition, believable natural or street lighting, and minimally staged real-world context. Preserve the offhand, in-the-moment quality of a real casual photo rather than turning it into editorial street photography.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'rear_camera_phone_photo',
        'label': 'Rear Camera Phone Photo [photo] [mobile]',
        'tags': ['photo', 'mobile'],
        'description': 'Rear-phone-camera photo style with practical handheld framing, clearer sensor detail, and real-world smartphone realism.',
        'instruction': 'Render as a rear-camera smartphone photo with believable handheld composition, natural lighting, and realistic mobile-camera image behavior. Preserve the everyday feel of a phone picture while keeping the subject readable and the background naturally integrated.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'restaurant_candid_phone_photo',
        'label': 'Restaurant Candid Phone Photo [photo] [candid]',
        'tags': ['photo', 'candid'],
        'description': 'Candid restaurant phone-photo style with ambient practical lighting, table-context realism, and spontaneous social-media authenticity.',
        'instruction': 'Render as a casual restaurant phone photo with warm ambient light, natural table or seating context, believable handheld composition, and social-photo realism. Preserve candid mood and environmental authenticity without turning it into professional food or hospitality advertising.',
        'main_category': 'Casual Phone-Photo Realism',
    },
    {
        'key': 'selfie_photo_front_camera',
        'label': 'Selfie Photo Front Camera [photo] [mobile]',
        'tags': ['photo', 'mobile'],
        'description': "Front-camera selfie-photo style with arm's-length framing, casual realism, and native smartphone perspective.",
        'instruction': 'Render as a front-camera selfie photo with believable phone-lens perspective, natural skin response, casual composition, and the slight imperfections of a real smartphone capture. Preserve spontaneity, personal presence, and natural background context rather than turning it into studio portrait photography.',
        'main_category': 'Casual Phone-Photo Realism',
    },
]
