from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'render_3d_cartoon',
        'label': '3D Cartoon [3d] [stylized]',
        'tags': ['3d', 'stylized'],
        'description': 'Stylized 3D toon look with smooth forms, expressive proportions, clean shading control, and high readability.',
        'instruction': 'Use toon-friendly shading, simplified but intentional material response, appealing proportions, and bright readable color grouping. Preserve playful clarity, clean edge handling, and stylized volume without collapsing into flatness or noisy semi-realistic surfacing.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'render_3d_realistic',
        'label': '3D Render [3d] [cgi]',
        'tags': ['3d', 'cgi'],
        'description': 'Modern high-quality CGI rendering with dimensional lighting, physically plausible surfacing, and production-grade geometric clarity.',
        'instruction': 'Render with PBR-aware surfacing, coherent reflections, believable roughness response, clean GI-driven lighting separation, and crisp geometry. Preserve production-ready realism with stable materials, controlled contrast, and artifact-free rendering rather than exaggerated demo-reel gloss.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'character_turntable_render_style',
        'label': '3D Sculpt Turntable Style [3d] [sculpt]',
        'tags': ['3d', 'sculpt'],
        'description': 'Turntable-ready sculpt presentation style with neutral lighting, form clarity, and model-review readability.',
        'instruction': 'Render as a sculpt turntable or turntable-ready presentation with clean neutral lighting, unobtrusive background, and strong emphasis on form and surface transitions. Preserve sculpt readability, silhouette clarity, and material neutrality rather than cinematic mood or beauty-shot styling.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'cad_product_render',
        'label': 'CAD Product Render [3d] [industrial]',
        'tags': ['3d', 'industrial'],
        'description': 'Industrial CAD-product render style with precision geometry, controlled materials, and engineering-grade presentation clarity.',
        'instruction': 'Render as an industrial product visualization with precise geometry, clean material behavior, and strong form readability suitable for design review or marketing. Preserve engineering discipline and product realism without unnecessary cinematic treatment.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'clay_render_zbrush_style',
        'label': 'Clay Render / ZBrush Style [3d] [sculpt]',
        'tags': ['3d', 'sculpt'],
        'description': 'Clay-render sculpt style with neutral material presentation, strong form readability, and subdivision-surface clarity.',
        'instruction': 'Render as a clay-style digital sculpt with a neutral matte material, soft controlled lighting, and high emphasis on silhouette, planes, and surface anatomy. Preserve sculptural readability and clean form analysis without texture distraction or polished production materials.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'claymation',
        'label': 'Claymation [3d] [stop-motion]',
        'tags': ['3d', 'stop-motion'],
        'description': 'Stop-motion clay aesthetic with handmade irregularities, tactile surfaces, miniature staging, and practical craft charm.',
        'instruction': 'Introduce subtle handcrafted asymmetry, matte clay texture, finger-formed surface cues, and miniature-stage lighting so the result reads like practical stop-motion craft. Preserve playful material tactility and physical presence rather than polished CG smoothness.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'family_animation_pixar_like',
        'label': 'Family Animation (Pixar-like) [animation] [stylized]',
        'tags': ['animation', 'stylized'],
        'description': 'Warm family-animation styling with appealing shapes, soft global illumination, emotionally clear color design, and polished character readability.',
        'instruction': 'Use a polished family-animation look with appealing proportions, clean surfacing, expressive silhouettes, and cinematic soft lighting. Preserve warmth, charm, and emotional clarity through shape design, material softness, and readable facial expression, while avoiding direct references to specific trademarked characters or franchises.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'hard_surface_3d_render',
        'label': 'Hard Surface 3D Render [3d] [mechanical]',
        'tags': ['3d', 'mechanical'],
        'description': 'Hard-surface render style with crisp geometry, material control, and industrial-design readability.',
        'instruction': 'Render as a hard-surface 3D object with sharp geometry, precise bevel behavior, controlled reflections, and strong structural readability. Preserve functional detailing and surface hierarchy without cluttering the design with unnecessary grime or sci-fi ornament.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'low_poly_3d',
        'label': 'Low Poly 3D [3d] [stylized]',
        'tags': ['3d', 'stylized'],
        'description': 'Low-poly 3D style with faceted geometry, simplified surfaces, clean planes, and readable stylized volume.',
        'instruction': 'Render with visible low-poly structure, economical geometry, simplified materials, and clear form planes. Preserve stylized dimensionality and clean color grouping without smoothing away the faceted construction.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'miniature_model_render',
        'label': 'Miniature Model Render [3d] [miniature]',
        'tags': ['3d', 'miniature'],
        'description': 'Miniature-model render style with scaled physicality, tabletop-display charm, and controlled presentation lighting.',
        'instruction': 'Render as a miniature model with believable small-scale material response, display-ready composition, and clear handcrafted or collectible presence. Preserve readable form, miniature scale cues, and polished presentation without flattening it into full-scale realism.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'render_pass_clay_preview',
        'label': 'Render Pass / Clay Preview [3d] [technical]',
        'tags': ['3d', 'technical'],
        'description': 'Technical preview-render style with neutral material override, lighting clarity, and form-focused asset review presentation.',
        'instruction': 'Render as a technical clay or preview pass with neutral shading, strong silhouette separation, and minimal scene distraction. Preserve model form, topology-driven shape readability, and presentation neutrality rather than textured hero rendering.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'stylized_character_render',
        'label': 'Stylized Character Render [3d] [character]',
        'tags': ['3d', 'character'],
        'description': 'Stylized-character 3D render style with appealing shapes, readable materials, and polished presentation clarity.',
        'instruction': 'Render as a polished stylized 3D character with clear shape language, readable materials, appealing proportions, and strong focal presentation. Preserve character charm and production-friendly clarity without muddy surfacing or generic semi-realistic noise.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'toy_collectible_render',
        'label': 'Toy Collectible Render [3d] [collectible]',
        'tags': ['3d', 'collectible'],
        'description': 'Collectible-toy render style with premium product finish, simplified material appeal, and display-ready clarity.',
        'instruction': 'Render as a premium toy or collectible figure with clean silhouette, polished material treatment, and strong display-ready presentation. Preserve toy-like proportions and collectible-market polish without losing sculpt readability or object identity.',
        'main_category': '3D / CGI / Stylized 3D',
    },
    {
        'key': 'voxel_art',
        'label': 'Voxel Art [3d] [voxel]',
        'tags': ['3d', 'voxel'],
        'description': 'Voxel-based 3D style with blocky construction, grid-based form logic, and playful dimensional clarity.',
        'instruction': 'Render using voxel logic with visible cube-based construction, simple material treatment, and clear block-structured silhouettes. Preserve grid readability and volumetric charm without smoothing away the voxel identity.',
        'main_category': '3D / CGI / Stylized 3D',
    },
]
