from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'armor_fit_base',
        'label': 'Armor Fit Base [character] [game-dev]',
        'tags': ['character', 'game-dev'],
        'description': 'Neutral armor-fit base style for character outfitting, gear layering, and modular protective-equipment development.',
        'instruction': 'Render as a neutral character base specifically intended for armor fitting, with clean body landmarks, strong silhouette readability, and neutral stance suitable for modular equipment design. Preserve production-ready anatomy, shoulder/torso/hip structure, and unobstructed surfaces without fashion styling or dramatic posing.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_apose',
        'label': 'Character A-Pose [character] [reference]',
        'tags': ['character', 'reference', 'apose', 'model-sheet', 'game-dev'],
        'description': 'Neutral full-body A-pose reference style for modeling, rigging, clothing fit, and character-sheet production.',
        'instruction': 'Render as a clean character reference in a neutral A-pose, with the arms angled slightly downward away from the torso and the legs clearly separated for silhouette readability. Use even studio lighting, minimal background distraction, centered framing, and proportionally accurate full-body presentation. Preserve anatomical clarity, clean joint landmarks, and unobstructed body contours so the image is useful for modeling, rigging, clothing design, and production reference. Keep the pose neutral, symmetrical, functional, and non-dramatic, avoiding perspective distortion, action posing, glamor styling, or cinematic mood lighting.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_anatomy_base',
        'label': 'Character Anatomy Base [character] [reference]',
        'tags': ['character', 'reference', 'anatomy', 'model-sheet', 'game-dev'],
        'description': 'Neutral full-body anatomical character-reference style for 3D modeling, rigging, and clothing workflows, with clean proportions, unobstructed body landmarks, and production-ready readability.',
        'instruction': 'Render as a neutral anatomical character base for game development and 3D production. Show the full body clearly with unobstructed proportions, accurate anatomy, and clean surface readability for later clothing, rigging, and asset development. Use a neutral studio setup, even shadow-controlled lighting, minimal background distraction, and front / side / back or orthographic-style presentation when relevant. Keep the pose relaxed, symmetrical, and functional for modeling reference, such as A-pose or T-pose, with arms slightly away from the torso and legs clearly separated for silhouette readability. Preserve realistic body structure, muscle and fat distribution, joint landmarks, torso rhythm, limb length, hands, feet, neck, and facial proportion so the character can be used as a reliable base mesh guide. Avoid glamor lighting, harsh shadows, and exaggerated anatomy. Prioritize anatomical consistency, modeling clarity, and production usefulness over fashion, mood, or dramatic storytelling.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_anatomy_base_nude',
        'label': 'Character Anatomy Nude Base [character] [reference]',
        'tags': ['character', 'reference', 'anatomy', 'model-sheet', 'game-dev', 'nude'],
        'description': 'Nude full-body anatomical character-reference style for 3D modeling, rigging, and clothing workflows, with clean proportions, unobstructed body landmarks, and production-ready readability.',
        'instruction': 'Render as a naked anatomical character base for game development and 3D production. Show the full body clearly with unobstructed proportions, accurate anatomy, and clean surface readability for later clothing, rigging, and asset development. Remove items, hair, accessories, clothing, etc., unless instructed otherwise. Use a neutral studio setup, even shadow-controlled lighting, and minimal background distraction. Keep the pose relaxed, symmetrical, and functional for modeling reference, such as A-pose or T-pose, with arms slightly away from the torso and legs clearly separated for silhouette readability. Preserve realistic body structure, muscle and fat distribution, joint landmarks, torso rhythm, limb length, hands, feet, neck, and facial proportion so the character can be used as a reliable base mesh guide. Avoid glamor lighting, harsh shadows, and exaggerated anatomy. Prioritize anatomical consistency, modeling clarity, and production usefulness over fashion, mood, or dramatic storytelling.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_expression_sheet',
        'label': 'Character Expression Sheet [character] [reference]',
        'tags': ['character', 'reference'],
        'description': 'Expression-sheet style showing multiple facial emotions with clean consistency, design clarity, and animation-friendly readability.',
        'instruction': 'Render as a character expression sheet with multiple clear emotional states, consistent head structure, clean spacing, and readable variation in brows, eyes, mouth, and facial tension. Preserve character identity and production-sheet clarity without decorative composition noise.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_height_comparison_sheet',
        'label': 'Character Height Comparison Sheet [character] [reference]',
        'tags': ['character', 'reference'],
        'description': 'Height-comparison sheet style with aligned scale, lineup clarity, and roster-design readability.',
        'instruction': 'Render as a height comparison lineup with multiple characters aligned to a common ground plane and scale reference. Preserve consistent posture, silhouette clarity, and easy visual comparison without cinematic posing or perspective distortion.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_multiview_10',
        'label': 'Character Multiview 10 Angles [character] [turnaround]',
        'tags': ['character', 'turnaround', 'reference', 'multiview', 'game-dev'],
        'description': 'Comprehensive multiview character sheet showing front, back, left side, right side, front-left, front-right, back-left, back-right, top birdseye, and bottom views for advanced production reference.',
        'instruction': 'Render as a ten-angle character reference sheet including front, back, left side, right side, front-left, front-right, back-left, back-right, top birdseye, and bottom views. Keep every angle aligned, evenly lit, and presented at consistent scale with a clean neutral background. Preserve anatomical accuracy, proportion stability, and uninterrupted structural readability across all views so the sheet is reliable for modeling, rigging, sculpting, and technical review. Avoid dramatic perspective, mood lighting, or layout noise that interferes with reference clarity.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_multiview_4',
        'label': 'Character Multiview 4 Angles [character] [turnaround]',
        'tags': ['character', 'turnaround', 'reference', 'multiview', 'game-dev'],
        'description': 'Production multiview character sheet showing front, back, left side, and right side with aligned scale and clean technical readability.',
        'instruction': 'Render as a multiview character turnaround sheet with four aligned views: front, back, left side, and right side. Keep the character at consistent scale in every panel, with neutral pose, even studio lighting, unobtrusive background, and minimal cast-shadow distraction. Preserve anatomical consistency, silhouette clarity, and clean spacing between views so the sheet is suitable for modeling, texturing, rigging, and design review. Avoid perspective drift, dramatic camera angles, exaggerated styling, or layout clutter.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_multiview_8',
        'label': 'Character Multiview 8 Angles [character] [turnaround]',
        'tags': ['character', 'turnaround', 'reference', 'multiview', 'game-dev'],
        'description': 'Expanded multiview character sheet showing front, back, left side, right side, front-left, front-right, back-left, and back-right angles for production reference.',
        'instruction': 'Render as an eight-angle character turnaround sheet with front, back, left side, right side, front-left, front-right, back-left, and back-right views. Maintain consistent scale, neutral studio presentation, even lighting, and precise view separation so each angle reads clearly. Preserve anatomical continuity across all panels, stable body proportions, and reliable silhouette transitions between views. Keep the layout technical, clean, and production-friendly, avoiding cinematic framing, inconsistent lens behavior, or decorative background elements.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_tpose',
        'label': 'Character T-Pose [character] [reference]',
        'tags': ['character', 'reference', 'tpose', 'model-sheet', 'game-dev'],
        'description': 'Neutral full-body T-pose reference style for base-mesh generation, rigging, retopology, and technical character development.',
        'instruction': 'Render as a professional character reference in a strict T-pose, with the arms extended horizontally and the body centered in a neutral upright stance. Use controlled studio lighting, consistent scale, minimal shadows, and a plain background so the full silhouette and anatomical proportions are easy to read. Preserve accurate body landmarks, joint structure, clean limb separation, and stable perspective for modeling and technical production use. Avoid dramatic composition, emotional posing, fashion styling, foreshortening, or decorative atmosphere.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_back',
        'label': 'Character View Back [character] [reference]',
        'tags': ['character', 'reference', 'back-view', 'game-dev'],
        'description': 'Single back-view character reference with clear posterior anatomy, silhouette control, and technical readability.',
        'instruction': 'Render as a clean back-view character reference with centered alignment, neutral stance, even lighting, and plain background. Preserve back anatomy, shoulder and hip structure, leg silhouette, and overall proportion logic with high clarity. Keep the presentation technical and production-friendly, avoiding dramatic composition, decorative atmosphere, or inconsistent perspective.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_back_left',
        'label': 'Character View Back-Left [character] [reference]',
        'tags': ['character', 'reference', 'back-left-view', 'game-dev'],
        'description': 'Three-quarter back-left character reference with clear posterior volume transition and technical readability.',
        'instruction': 'Render as a back-left three-quarter character reference with neutral stance, even studio lighting, and a clean background. Preserve back anatomy, shoulder and hip rotation, leg silhouette, and stable volumetric transition from back to side. Keep the presentation technical and production-useful rather than cinematic or stylized.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_back_right',
        'label': 'Character View Back-Right [character] [reference]',
        'tags': ['character', 'reference', 'back-right-view', 'game-dev'],
        'description': 'Three-quarter back-right character reference with stable structural readability and production-ready rotational clarity.',
        'instruction': 'Render as a back-right three-quarter character reference with neutral pose, even lighting, centered composition, and a plain background. Preserve posterior anatomy, silhouette logic, and consistent volume transition from back to side. Avoid decorative atmosphere, dramatic framing, or emotional posing.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_bottom',
        'label': 'Character View Bottom [character] [reference]',
        'tags': ['character', 'reference', 'bottom-view', 'game-dev'],
        'description': 'Bottom-up character reference for underside form visibility, silhouette verification, and advanced production review.',
        'instruction': 'Render as a bottom-view character reference with stable underside visibility, clean form separation, even lighting, and plain technical presentation. Preserve anatomical structure, volume readability, and accurate underside proportions for modeling or review purposes. Keep the result functional, neutral, and non-dramatic, avoiding stylized foreshortening or theatrical perspective distortion.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_front',
        'label': 'Character View Front [character] [reference]',
        'tags': ['character', 'reference', 'front-view', 'game-dev'],
        'description': 'Single front-view character reference with centered alignment, proportion clarity, and production-ready silhouette readability.',
        'instruction': 'Render as a clean front-view character reference with centered framing, neutral stance, even studio lighting, and plain background. Preserve symmetrical readability, proportion accuracy, and unobstructed body landmarks so the result works for character design, modeling, and review. Avoid dramatic camera tilt, action posing, stylized perspective, or distracting environmental context.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_front_left',
        'label': 'Character View Front-Left [character] [reference]',
        'tags': ['character', 'reference', 'front-left-view', 'game-dev'],
        'description': 'Three-quarter front-left character reference with clean rotational readability and consistent production presentation.',
        'instruction': 'Render as a front-left three-quarter character reference with stable rotation, neutral stance, even lighting, and minimal background distraction. Preserve anatomical continuity, clean silhouette overlap, and accurate volume transition from front to side. Keep the angle clear and technical, not cinematic or overly posed.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_front_right',
        'label': 'Character View Front-Right [character] [reference]',
        'tags': ['character', 'reference', 'front-right-view', 'game-dev'],
        'description': 'Three-quarter front-right character reference with stable rotational clarity and production-ready body readability.',
        'instruction': 'Render as a front-right three-quarter character reference with controlled rotation, neutral stance, even studio lighting, and plain background. Preserve structural continuity, silhouette readability, and believable volumetric transition between front and side planes. Avoid action posing, dramatic lensing, or mood-first presentation.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_left_side',
        'label': 'Character View Left Side [character] [reference]',
        'tags': ['character', 'reference', 'left-side-view', 'game-dev'],
        'description': 'Single left-side character reference with clean profile readability, proportion control, and modeling-friendly silhouette clarity.',
        'instruction': 'Render as a clean left-side character reference with strict profile orientation, neutral posture, even studio lighting, and a minimal background. Preserve profile anatomy, body rhythm, head-to-foot proportion flow, and clear front-back silhouette relationships. Avoid perspective distortion, action posing, and cinematic framing.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_right_side',
        'label': 'Character View Right Side [character] [reference]',
        'tags': ['character', 'reference', 'right-side-view', 'game-dev'],
        'description': 'Single right-side character reference with precise profile structure, clean silhouette readability, and production-oriented presentation.',
        'instruction': 'Render as a clean right-side character reference with strict profile orientation, neutral posture, even studio lighting, and a plain background. Preserve profile anatomy, body rhythm, head-to-foot proportion flow, and accurate silhouette transition from front to back. Keep the image technical, stable, and modeling-friendly rather than dramatic or stylized.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'character_view_top_birdseye',
        'label': 'Character View Top / Birdseye [character] [reference]',
        'tags': ['character', 'reference', 'top-view', 'birdseye', 'game-dev'],
        'description': 'Top-down birdseye character reference for overhead form analysis, silhouette planning, and production geometry review.',
        'instruction': 'Render as a top-down birdseye character reference with clear overhead visibility, proportionally consistent foreshortening, even controlled lighting, and minimal background distraction. Preserve readable shoulder width, torso depth, limb spacing, head shape, and overall footprint for modeling and gameplay-readability use. Keep the view technical and legible rather than dramatic or cinematic.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'clothing_layer_base',
        'label': 'Clothing Layer Base [character] [apparel]',
        'tags': ['character', 'apparel'],
        'description': 'Neutral apparel-base style for layering garments, testing outfit silhouettes, and maintaining clean body-reference consistency.',
        'instruction': 'Render as a clean clothing-layer base with neutral anatomy, relaxed functional pose, and unobstructed body contours appropriate for fashion or game-outfit development. Preserve proportion clarity, garment-fit usefulness, and consistent base-body structure without decorative accessories or stylistic distractions.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'face_planes_study',
        'label': 'Face Planes Study [anatomy] [reference]',
        'tags': ['anatomy', 'reference'],
        'description': 'Facial-plane study style with simplified structural breakdown, lighting-readiness, and sculptural anatomy clarity.',
        'instruction': 'Render as a face-planes study emphasizing the major structural planes of the forehead, cheeks, nose, jaw, and chin. Preserve anatomical clarity, neutral lighting, and educational simplification useful for painting, sculpting, and character construction.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'fat_distribution_study',
        'label': 'Fat Distribution Study [anatomy] [reference]',
        'tags': ['anatomy', 'reference'],
        'description': 'Anatomical fat-distribution study style showing volume placement, body-mass variation, and realistic human-form readability.',
        'instruction': 'Render as an anatomy study focused on fat distribution across the body, preserving realistic volume placement, body-type variation, and proportion logic. Keep the presentation clinical, neutral, and educational rather than glamorized or exaggerated.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'footwear_turnaround',
        'label': 'Footwear Turnaround [character] [reference]',
        'tags': ['character', 'reference'],
        'description': 'Footwear-turnaround style with multi-angle shoe readability, sole detail visibility, and product-design clarity.',
        'instruction': 'Render as a footwear turnaround sheet with front, side, rear, and outsole or top views as needed. Preserve construction detail, silhouette clarity, material distinction, and clean product-like presentation without fashion-editorial styling.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'hair_style_sheet',
        'label': 'Hair Style Sheet [character] [reference]',
        'tags': ['character', 'reference'],
        'description': 'Hairstyle reference-sheet style with multi-angle grooming clarity, silhouette readability, and production design support.',
        'instruction': 'Render as a hairstyle sheet with clear front, side, back, and three-quarter visibility where useful. Preserve hair volume, silhouette, parting logic, length relationships, and strand grouping in a clean presentation suited for character design and modeling reference.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'hand_pose_sheet',
        'label': 'Hand Pose Sheet [character] [reference]',
        'tags': ['character', 'reference'],
        'description': 'Hand-pose reference style with anatomical clarity, gesture variety, and clean production-sheet presentation.',
        'instruction': 'Render as a hand pose sheet with multiple hand positions shown clearly, including relaxed, open, closed, and gesture-specific poses where relevant. Preserve finger anatomy, joint articulation, and readable spacing with neutral presentation and minimal background distraction.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'head_turnaround_sheet',
        'label': 'Head Turnaround Sheet [character] [reference]',
        'tags': ['character', 'reference'],
        'description': 'Head-turnaround sheet style with multi-angle cranial readability, facial consistency, and production modeling support.',
        'instruction': 'Render as a head turnaround sheet with front, side, back, and three-quarter views aligned consistently and evenly lit. Preserve facial proportions, skull shape, ear placement, and hairstyle consistency so the sheet is reliable for modeling and character production.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'muscle_anatomy_view',
        'label': 'Muscle Anatomy View [anatomy] [reference]',
        'tags': ['anatomy', 'reference', 'muscle', 'medical', 'character'],
        'description': 'Detailed muscular-anatomy visualization style showing the body at the muscle level for form study, character design, and modeling reference.',
        'instruction': 'Render as a realistic muscle-anatomy reference showing the body at the muscular layer rather than surface skin detail. Emphasize major muscle groups, tendon transitions, anatomical rhythm, and clean educational readability with controlled lighting and neutral presentation. Keep the style clinical, structural, and production-useful, preserving muscle separation, proportional accuracy, and clear labeling space if needed. Avoid gore, injury, sensational medical imagery, or decorative cinematic atmosphere.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'skeletal_anatomy_view',
        'label': 'Skeletal Anatomy View [anatomy] [reference]',
        'tags': ['anatomy', 'reference', 'skeleton', 'medical', 'character'],
        'description': 'Realistic skeletal-reference style showing bone structure, joint alignment, and clinical anatomical clarity for study and production use.',
        'instruction': 'Render as a realistic skeletal anatomy reference with clear bone structure, joint articulation, proportion logic, and clinical readability. Emphasize skull, ribcage, spine, pelvis, limb bones, hands, and feet with stable educational presentation and neutral studio-like lighting. Keep the result technical, clean, and anatomy-focused, avoiding horror styling, gore, decorative x-ray effects, or dramatic atmosphere.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
    {
        'key': 'vein_surface_anatomy_study',
        'label': 'Vein / Surface Anatomy Study [anatomy] [reference]',
        'tags': ['anatomy', 'reference'],
        'description': 'Surface-anatomy study style showing veins, tendons, and subtle external structural landmarks with educational clarity.',
        'instruction': 'Render as a surface-anatomy study highlighting veins, tendons, bony landmarks, and muscle-surface transitions in a realistic, readable way. Preserve anatomical accuracy and clean educational presentation without gore, injury, or theatrical medical styling.',
        'main_category': 'Character Reference / Turnarounds / Anatomy',
    },
]
