from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'agenda_meeting_notes_template',
        'label': 'Agenda / Meeting Notes Template [document] [business]',
        'tags': ['document', 'business'],
        'description': 'Business-notes template style with structured sections, clear hierarchy, and practical meeting-readability.',
        'instruction': 'Design as an agenda or meeting-notes template with clearly defined sections for attendees, topics, decisions, action items, and next steps. Preserve practical usability, organized spacing, and fast in-meeting readability without unnecessary decoration.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'case_study_layout',
        'label': 'Case Study Layout [document] [business]',
        'tags': ['document', 'business'],
        'description': 'Case-study layout style with narrative structure, metric clarity, and professional editorial-business presentation.',
        'instruction': 'Design as a case study with clear sections for challenge, approach, results, and outcomes, supported by strong headings and easy-to-scan visual hierarchy. Preserve business polish, metric readability, and document credibility without turning it into a generic brochure.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'id_card_badge_design',
        'label': 'ID Card / Badge Design [design] [business]',
        'tags': ['design', 'business', 'badge', 'id-card'],
        'description': 'Identification-card style with strong hierarchy, secure-layout clarity, and compact production-ready readability.',
        'instruction': 'Design as an ID card or badge with clear name, title, role, and photo hierarchy, along with clean branding and practical small-format structure. Preserve scannability, card usability, and organized layout while avoiding decorative clutter that weakens function.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'invoice_template',
        'label': 'Invoice / Receipt Template [design] [document]',
        'tags': ['design', 'document', 'invoice', 'business'],
        'description': 'Business-document template style with clean tabular clarity, payment hierarchy, and practical administrative readability.',
        'instruction': 'Design as an invoice or receipt template with strong alignment, readable totals hierarchy, clear billing sections, and professional document structure. Preserve fast scanability, clean accounting logic, and print/digital usability without decorative distraction.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'one_page_sell_sheet',
        'label': 'One-Page Sell Sheet [document] [marketing]',
        'tags': ['document', 'marketing'],
        'description': 'Sell-sheet style with persuasive hierarchy, concise product positioning, and business-ready promotional clarity.',
        'instruction': 'Design as a one-page sell sheet with strong headline hierarchy, clear product or service value framing, readable supporting sections, and polished marketing layout. Preserve fast scanability and persuasive clarity without crowding the page with too much copy or visual noise.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'planner_page_layout',
        'label': 'Planner Page Layout [document] [productivity]',
        'tags': ['document', 'productivity'],
        'description': 'Planner-page style with schedule clarity, writing space, and balanced productivity-focused layout.',
        'instruction': 'Design as a planner page with clearly separated scheduling blocks, task zones, notes areas, and strong visual structure for daily or weekly planning. Preserve writing usability, spacing balance, and calm clarity without overcrowding the page.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'proposal_cover_sheet',
        'label': 'Proposal Cover Sheet [document] [business]',
        'tags': ['document', 'business'],
        'description': 'Professional proposal-cover style with clean title hierarchy, executive polish, and client-ready presentation.',
        'instruction': 'Design as a proposal cover page with clear title treatment, brand alignment, concise supporting text, and polished professional spacing. Preserve readability, trust-building structure, and business-appropriate restraint without poster-like visual overload.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'report_cover_page',
        'label': 'Report Cover Page [document] [business]',
        'tags': ['document', 'business'],
        'description': 'Report-cover style with formal information hierarchy, clean layout logic, and polished document presentation.',
        'instruction': 'Design as a report cover with clear title, subtitle, organization, and date hierarchy, supported by a clean professional visual structure. Preserve strong readability, document seriousness, and executive clarity without decorative clutter.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'resume_layout',
        'label': 'Resume / CV Layout [design] [document]',
        'tags': ['design', 'document', 'resume', 'business'],
        'description': 'Professional resume-layout style with strong information hierarchy, clean typography, and recruiter-friendly scanability.',
        'instruction': 'Design as a resume or CV layout with disciplined typographic hierarchy, clear sectioning, strong alignment, and high readability. Preserve document professionalism, efficient information scanning, and clean structure without decorative clutter or style choices that weaken usability.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'whitepaper_layout',
        'label': 'Whitepaper Layout [document] [editorial]',
        'tags': ['document', 'editorial'],
        'description': 'Whitepaper style with formal editorial structure, strong readability, and research-oriented document hierarchy.',
        'instruction': 'Design as a whitepaper layout with disciplined headings, supporting charts or callouts where useful, generous margins, and serious editorial clarity. Preserve intellectual credibility, long-form readability, and professional structure without decorative marketing excess.',
        'main_category': 'Document / Business Templates',
    },
    {
        'key': 'worksheet_workbook_page',
        'label': 'Worksheet / Workbook Page [document] [education]',
        'tags': ['document', 'education'],
        'description': 'Workbook-page style with instructional clarity, writing-friendly spacing, and structured educational layout.',
        'instruction': 'Design as a worksheet or workbook page with clear exercise sections, response areas, instructional hierarchy, and student-friendly readability. Preserve clean educational structure and writing usability without decorative distractions that weaken learning focus.',
        'main_category': 'Document / Business Templates',
    },
]
