from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'background_removal_isolation',
        'label': 'Background Removal / Isolation [editing] [utility]',
        'tags': ['editing', 'utility'],
        'description': 'Clean isolation-edit style that removes the background while preserving subject edges, material detail, and original object integrity.',
        'instruction': 'Apply precise background removal so the subject is fully isolated with clean edges, preserved fine details, intact transparency-sensitive areas, and no contamination from the original background. Keep the subject unchanged in color, lighting, texture, and shape while avoiding haloing, edge damage, or unwanted cutout artifacts.',
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'expression_adjustment',
        'label': 'Expression Adjustment [editing] [portrait]',
        'tags': ['editing', 'portrait'],
        'description': 'Targeted expression-edit style that changes facial expression while preserving identity, anatomy, lighting, and image realism.',
        'instruction': "Adjust only the facial expression to match the requested emotion while preserving the subject's identity, age, facial structure, lighting, angle, and surrounding composition. Keep the result anatomically believable and subtle enough to feel natural, without altering hairstyle, pose, background, or unrelated features.",
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'image_upscale_detail_recovery',
        'label': 'Image Upscale / Detail Recovery [editing] [enhancement]',
        'tags': ['editing', 'enhancement'],
        'description': "Enhancement style focused on resolution improvement, detail recovery, and clean sharpening without changing the image's core identity.",
        'instruction': 'Enhance the image by increasing clarity, recovering fine detail, and improving apparent resolution while preserving the original composition, colors, lighting, and subject identity. Avoid oversharpening, synthetic textures, face drift, or hallucinated detail that changes the original image content.',
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'inpainting_fill_match',
        'label': 'Inpainting / Fill Match [editing] [repair]',
        'tags': ['editing', 'repair'],
        'description': 'Context-aware fill style that reconstructs missing or edited regions to match the existing image seamlessly and believably.',
        'instruction': "Rebuild the specified missing or edited area using surrounding context, matching the original image's perspective, materials, textures, color balance, and lighting behavior. Keep the repair invisible and scene-consistent, with no spill into unchanged areas and no stylistic drift away from the source image.",
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'lighting_match_relight',
        'label': 'Lighting Match / Relight [editing] [utility]',
        'tags': ['editing', 'utility'],
        'description': 'Controlled relighting style that changes lighting while preserving form, texture, subject identity, and scene consistency.',
        'instruction': 'Adjust the scene lighting or relight the subject to the requested look while preserving composition, anatomy, materials, and core identity. Keep shadows, highlights, and reflections physically plausible and coherent with the environment, avoiding overprocessed HDR effects or unintended changes to non-lighting attributes.',
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'material_swap',
        'label': 'Material Swap [editing] [precision]',
        'tags': ['editing', 'precision'],
        'description': 'Targeted material-swap style that changes only the specified material while preserving shape, lighting, and everything else unchanged.',
        'instruction': 'Replace only the user-specified material or surface finish while preserving form, geometry, object identity, lighting direction, reflections, and surrounding composition. Make the new material physically believable for the object, with correct texture response and highlight behavior, and avoid changing unrelated surfaces or scene structure.',
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'object_removal_cleanup',
        'label': 'Object Removal / Cleanup [editing] [retouch]',
        'tags': ['editing', 'retouch'],
        'description': 'Precision cleanup-edit style that removes unwanted objects while preserving scene consistency, lighting, texture, and composition.',
        'instruction': 'Remove the specified object or distraction cleanly while preserving the surrounding environment, materials, perspective, and lighting continuity. Fill the edited area so it blends naturally with adjacent surfaces and scene logic, avoiding obvious patching, repeated textures, warped structure, or unintended changes elsewhere in the image.',
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'pose_preservation_edit',
        'label': 'Pose Preservation Edit [editing] [consistency]',
        'tags': ['editing', 'consistency'],
        'description': 'Pose-preserving edit style that changes requested details while locking the original stance, body language, and composition.',
        'instruction': 'Apply the requested visual change while preserving the original pose, body orientation, framing, and compositional balance. Keep anatomy, gesture, and spatial relationships unchanged unless explicitly requested, avoiding unintended repositioning, limb drift, or camera-angle shifts.',
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'seamless_outpainting',
        'label': 'Seamless Outpainting [editing] [extension]',
        'tags': ['editing', 'extension'],
        'description': 'Outpainting style that extends the image naturally while matching perspective, lighting, style, and scene logic.',
        'instruction': "Extend the image outward seamlessly, preserving the source image's perspective, lighting, material language, atmospheric treatment, and compositional intent. The new content should feel like a natural continuation of the original frame, without visible seams, repetition artifacts, or stylistic mismatch.",
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'style_preserving_edit',
        'label': 'Style-Preserving Edit [editing] [consistency]',
        'tags': ['editing', 'consistency'],
        'description': "Consistency-preserving edit style that applies requested changes while maintaining the original image's visual style and rendering language.",
        'instruction': "Apply the user's requested edit while preserving the original artwork or image style, including line quality, rendering approach, color treatment, texture language, and composition logic. Avoid style drift, mixed-medium artifacts, or unrelated aesthetic changes beyond the requested modification.",
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'surface_cleanup_restoration',
        'label': 'Surface Cleanup / Restoration [editing] [retouch]',
        'tags': ['editing', 'retouch'],
        'description': 'Restoration-focused edit style that cleans wear, stains, damage, or noise while preserving original material realism and structure.',
        'instruction': 'Clean and restore the specified surface by removing dirt, scratches, stains, tears, or aging artifacts while preserving authentic material detail, geometry, and lighting. Keep the result realistic and controlled, avoiding plastic over-smoothing, loss of texture identity, or spill into unaffected regions.',
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'target_recoloring',
        'label': 'Target Recoloring [editing] [precision]',
        'tags': ['editing', 'precision', 'recolor', 'product', 'design'],
        'description': 'Precision recoloring style for targeted color edits that change only the requested area while preserving material, lighting, texture, and everything else unchanged.',
        'instruction': 'Apply highly controlled target recoloring to only the user-specified object, region, garment, material, or surface while preserving the original composition, lighting, shading, reflections, texture detail, edges, background, and all non-target elements. Keep the recolor physically believable for the material, with consistent highlight behavior and unchanged form readability. Avoid spill into adjacent areas, avoid changing unrelated objects, and do not alter camera angle, layout, structure, or image mood beyond the requested color update.',
        'main_category': 'Editing / Utility Styles',
    },
    {
        'key': 'texture_transfer',
        'label': 'Texture Transfer [editing] [precision]',
        'tags': ['editing', 'precision'],
        'description': 'Controlled texture-transfer style that applies a new surface texture while preserving base shape, lighting, and object continuity.',
        'instruction': 'Transfer the requested texture onto the target surface while preserving the original object form, scale logic, edge integrity, and lighting behavior. Keep the texture aligned to the surface correctly and avoid accidental color, geometry, or composition changes outside the designated target area.',
        'main_category': 'Editing / Utility Styles',
    },
]
