from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'apex_yard_hardcore',
        'label': 'Apex Yard (Hardcore) [game] [urban] [sports]',
        'tags': ['game', 'urban', 'sports', 'gritty', 'hardcore'],
        'description': 'Hard-edged underground football style with raw urban textures, physically imposing athletes, dangerous improvised arenas, and high-contrast cinematic sports presentation.',
        'instruction': 'Render in a hard-edged Apex Yard style with underground football energy, raw city grit, and premium game-art clarity. Emphasize improvised indoor and outdoor arenas built from chain-link fences, concrete barriers, graffiti walls, industrial roll-up doors, rusted beams, barrels, tires, broken asphalt, wet reflective ground, and harsh scoreboard lighting. Keep the world dirty, bruised, and lived-in, but always readable for gameplay and hero-shot presentation. Characters should be physically distinct and roster-ready with varied body builds from agile to massive, visible conditioning, intimidating confidence, and street-performance styling that combines compression gear, cropped jerseys, wraps, tattoos, chains, and battle-worn athletic apparel. Use charcoal, asphalt gray, black, dirty white, rust, and concrete as the core palette, with bold orange-yellow practical light, red scoreboard accents, and selective cool cyan edge-light to create contrast. Preserve cinematic lighting, strong rim separation, wet-surface bounce, readable silhouettes, and premium material response across skin, fabric, concrete, metal, and rubber. Props and assets should feel brutal, utilitarian, and urban-athletic rather than decorative: fencing, bleachers, barriers, training gear, posters, signage, painted yard lines, and impact-worn equipment. Avoid polished stadium luxury, clean suburban fields, generic esports futurism, cartoon softness, or overdesigned sci-fi clutter.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'arcade_sports_game_art',
        'label': 'Arcade Sports Game Art [game] [sports]',
        'tags': ['game', 'sports'],
        'description': 'Arcade-sports game-art style with exaggerated energy, readable athletic action, and bold commercial sport-game polish.',
        'instruction': 'Render as arcade-sports game art with dynamic movement, punchy color contrast, strong athlete silhouette clarity, and entertainment-forward sports presentation. Preserve instant readability and action excitement without turning the image into messy motion blur or generic realism.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'boss_character_key_art',
        'label': 'Boss Character Key Art [game] [character]',
        'tags': ['game', 'character'],
        'description': 'Boss-character key-art style with dominant scale, strong menace, and premium promotional encounter readability.',
        'instruction': 'Render as boss-character key art with an imposing silhouette, high-impact design hierarchy, strong focal composition, and premium game-promo polish. Preserve threat, scale, and memorable identity without obscuring the character under excessive effects or environment clutter.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'dark_fantasy_game_art',
        'label': 'Dark Fantasy Game Art [game] [fantasy]',
        'tags': ['game', 'fantasy'],
        'description': 'Dark-fantasy game-art style with grim atmosphere, mythic menace, and readable high-impact world-building.',
        'instruction': 'Render in a dark-fantasy game-art style with moody lighting, gothic or corrupted material cues, dramatic silhouettes, and a sense of danger or decay. Preserve gameplay-readability, strong focal hierarchy, and premium game-art polish without collapsing into muddy darkness or generic horror noise.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'fighting_game_splash_art',
        'label': 'Fighting Game Splash Art [game] [combat]',
        'tags': ['game', 'combat'],
        'description': 'Fighting-game splash-art style with explosive pose language, strong silhouette impact, and character-first readability.',
        'instruction': 'Render as fighting-game splash art with high-impact posing, clear anatomy, dramatic energy arcs, and powerful focal hierarchy. Preserve instantly readable character identity and premium promotional polish without muddy effects or overcrowded background action.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'graffiti_street_art',
        'label': 'Graffiti / Street Art [urban] [street-art]',
        'tags': ['urban', 'street-art'],
        'description': 'Street-art style with bold spray textures, graphic energy, layered surface wear, and public-space attitude.',
        'instruction': 'Render with graffiti or street-art logic using bold mark-making, aerosol texture cues, layered paint application, and urban surface integration. Preserve expressive energy and wall-readability without turning it into clean vector design.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'hero_shooter_key_art',
        'label': 'Hero Shooter Key Art [game] [action]',
        'tags': ['game', 'action'],
        'description': 'Hero-shooter key-art style with character-forward composition, faction clarity, and high-energy commercial game presentation.',
        'instruction': 'Render as hero-shooter key art with dominant character silhouettes, strong pose language, faction or role readability, and bold color separation. Preserve premium key-art polish, team readability, and action-forward energy without cluttering the frame with too many competing effects.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'jrpg_character_art',
        'label': 'JRPG Character Art [game] [jrpg]',
        'tags': ['game', 'jrpg'],
        'description': 'JRPG-character style with expressive design language, costume clarity, and polished key-visual appeal.',
        'instruction': 'Render as JRPG character art with readable costume design, elegant silhouette, expressive face and pose language, and polished fantasy or sci-fi identity. Preserve collectible character clarity and premium role-based design without overloading the costume with unreadable ornament.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'loot_item_render',
        'label': 'Loot Item Render [game] [asset]',
        'tags': ['game', 'asset'],
        'description': 'Game-loot item render style with rarity signaling, clean isolated presentation, and high-readability asset appeal.',
        'instruction': 'Render as a game loot-item asset with clear shape identity, rarity or value cues, readable materials, and clean isolated presentation. Preserve strong icon-readability and item desirability without overcrowding the object with unnecessary detail.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'cyberpunk_neon',
        'label': 'Neon Cyberpunk [stylized] [lighting]',
        'tags': ['stylized', 'lighting'],
        'description': 'Neon-forward futuristic look with emissive accents, reflective surfaces, atmospheric haze, and controlled high-contrast color separation.',
        'instruction': 'Use emissive lighting interplay, reflective materials, wet or glossy surfaces where appropriate, and bold but disciplined palette separation. Preserve edge readability, spatial depth, and visual hierarchy instead of collapsing into neon color clutter.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'pixel_art',
        'label': 'Pixel Art [pixel-art] [game]',
        'tags': ['pixel-art', 'game'],
        'description': 'Retro pixel-grid styling with deliberate palette discipline, low-resolution abstraction, tile-aware clarity, and strong silhouette readability.',
        'instruction': 'Constrain forms to a visible pixel grid, simplify anti-aliasing, maintain strict palette logic, and prioritize shape readability at small scale. Keep detail economical, clusters intentional, and shading consistent with retro game-art logic rather than modern painted rendering.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'prop_pickup_icon_render',
        'label': 'Prop Pickup Icon Render [game] [asset]',
        'tags': ['game', 'asset'],
        'description': 'Pickup-icon style with compact silhouette, strong readability, and UI-friendly asset presentation.',
        'instruction': 'Render as a pickup or inventory icon asset with a bold clean silhouette, readable material cues, strong contrast, and compact composition suitable for UI display. Preserve instant recognizability and game-asset utility without decorative clutter.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'robotic_design',
        'label': 'Robotic Design [scifi] [mechanical]',
        'tags': ['scifi', 'mechanical'],
        'description': 'Mechanical robotics style with engineered joints, panel segmentation, functional material logic, and believable assembly structure.',
        'instruction': 'Emphasize mechanical plausibility with articulated joints, fasteners, access panels, material differentiation, and practical assembly logic. Keep the design visually coherent, structurally readable, and grounded in industrial function rather than ornamental complexity alone.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'sci_fi_concept',
        'label': 'Sci-Fi Concept [scifi] [concept]',
        'tags': ['scifi', 'concept'],
        'description': 'Futuristic concept-art style with functional design logic, advanced materials, readable silhouettes, and speculative world-building clarity.',
        'instruction': 'Frame as sci-fi concept design with believable technological structure, purposeful silhouette design, coherent materials, and selective detail focused on decision-making. Keep the result imaginative, internally consistent, and production-usable rather than random futurist noise.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'survival_horror_game_art',
        'label': 'Survival Horror Game Art [game] [horror]',
        'tags': ['game', 'horror'],
        'description': 'Survival-horror game-art style with oppressive atmosphere, tension-heavy lighting, and readable threat design.',
        'instruction': 'Render in a survival-horror game-art style with sparse light, environmental menace, believable decay, and strong tension-first composition. Preserve fear, space readability, and threat clarity without losing the scene in darkness or chaotic gore.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
    {
        'key': 'tactical_military_game_art',
        'label': 'Tactical Military Game Art [game] [military]',
        'tags': ['game', 'military'],
        'description': 'Tactical-military game-art style with disciplined gear realism, grounded environments, and mission-oriented visual clarity.',
        'instruction': 'Render in a tactical-military game-art style with believable gear, practical materials, grounded lighting, and mission-driven composition. Preserve realism, threat clarity, and readable squad or equipment hierarchy without drifting into exaggerated action-movie chaos.',
        'main_category': 'Game / World / Specialized Visual Styles',
    },
]
