from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'anime_illustration',
        'label': 'Anime Illustration [anime] [illustration]',
        'tags': ['anime', 'illustration'],
        'description': 'Modern anime-inspired illustration with expressive line work, controlled cel-shading, clean color blocking, and strong silhouette readability.',
        'instruction': 'Use anime-style line hierarchy, selective cel-shading, clean shape language, and controlled facial stylization. Keep anatomy, perspective, costume detail, and environment structure coherent while preserving expressive appeal, readable silhouettes, and polished color separation without muddy gradients or over-rendered realism.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'art_nouveau',
        'label': 'Art Nouveau [illustration] [decorative]',
        'tags': ['illustration', 'decorative'],
        'description': 'Art Nouveau style with flowing ornament, elegant contour rhythm, floral motifs, and graceful poster-like composition.',
        'instruction': 'Render with Art Nouveau-inspired line flow, decorative framing logic, stylized organic motifs, and balanced ornamental detail. Keep the image elegant, unified, and pattern-aware without overcrowding the composition.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'botanical_illustration',
        'label': 'Botanical Illustration [illustration] [scientific]',
        'tags': ['illustration', 'scientific'],
        'description': 'Botanical-illustration style with plant-structure accuracy, specimen clarity, and refined scientific presentation.',
        'instruction': 'Render as botanical illustration with accurate leaf, stem, flower, and root structure, balanced composition, and educational readability. Preserve specimen clarity and delicate natural detail without decorative over-stylization or painterly ambiguity.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'childrens_book_illustration',
        'label': "Children's Book Illustration [illustration] [storybook]",
        'tags': ['illustration', 'storybook'],
        'description': "Children's-book style with friendly forms, warm storytelling clarity, and page-friendly narrative readability.",
        'instruction': "Render as children's-book illustration with approachable characters, warm color design, soft but clear detail hierarchy, and inviting narrative composition. Preserve page-readability, emotional clarity, and charm without clutter or overly complex rendering.",
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'comic_book',
        'label': 'Comic Book [comic] [ink]',
        'tags': ['comic', 'ink'],
        'description': 'Graphic comic-book visual language with assertive inks, bold value separation, dynamic framing, and strong panel readability.',
        'instruction': 'Use punchy ink contours, graphic shadows, bold focal hierarchy, and energetic but coherent perspective. Keep action staging clear, silhouettes readable, and color or value grouping strong enough that the image feels immediately legible as a comic panel rather than a generic illustration.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'concept_art',
        'label': 'Concept Art [illustration] [concept]',
        'tags': ['illustration', 'concept'],
        'description': 'Production concept style focused on design readability, mood intent, world-building cues, and decision-ready visual development.',
        'instruction': 'Frame the output like studio concept art: readable forms, practical design logic, strong value grouping, and selective detail concentrated where design decisions matter most. Favor ideation clarity, material and scale cues, and art-direction usefulness over fully polished final-render decoration.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'cozy_interior_illustration',
        'label': 'Cozy Interior Illustration [interior] [illustration]',
        'tags': ['interior', 'illustration'],
        'description': 'Warm cozy-interior illustration style with inviting atmosphere, soft lighting, and lived-in spatial charm.',
        'instruction': 'Render as a cozy interior illustration with warm light pools, readable furniture grouping, tactile materials, and a calm domestic atmosphere. Preserve inviting composition, softness, and interior storytelling while keeping the room legible and uncluttered rather than overfilled with props.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'cutaway_illustration',
        'label': 'Cutaway Illustration [illustration] [technical]',
        'tags': ['illustration', 'technical'],
        'description': 'Cutaway-illustration style with readable internal structure, balanced exterior context, and explanatory visual clarity.',
        'instruction': 'Render as a cutaway illustration showing interior forms or mechanisms while preserving enough exterior structure for context. Keep the internal reveal clear, logically sectioned, and educationally readable without becoming visually confusing.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'editorial_illustration',
        'label': 'Editorial Illustration [illustration] [editorial]',
        'tags': ['illustration', 'editorial'],
        'description': 'Concept-driven editorial illustration with smart visual metaphor, clean composition, and publication-ready clarity.',
        'instruction': 'Use editorial-illustration logic with strong conceptual focus, simplified forms, restrained detail, and a clear central idea that reads immediately. Keep the image clever, readable, and magazine-appropriate rather than overly literal or over-rendered.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'fashion_illustration',
        'label': 'Fashion Illustration [illustration] [editorial]',
        'tags': ['illustration', 'editorial'],
        'description': 'Fashion-illustration style with garment emphasis, elegant figure stylization, and editorial presentation clarity.',
        'instruction': 'Render as fashion illustration with clear garment silhouette, expressive pose flow, refined line treatment, and premium editorial sensibility. Preserve fabric readability, figure elegance, and design focus without muddy rendering or excess scene clutter.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'isometric',
        'label': 'Isometric Illustration [illustration] [isometric]',
        'tags': ['illustration', 'isometric'],
        'description': 'Structured isometric visual language with stable projection logic, geometric precision, and clear scene readability.',
        'instruction': 'Keep isometric angle consistency, clear scale relationships, disciplined object grouping, and uncluttered scene layering. Favor precision, hierarchy, and readable geometry over perspective distortion or decorative chaos.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'line_art_clean',
        'label': 'Line Art (Clean) [line-art] [illustration]',
        'tags': ['line-art', 'illustration'],
        'description': 'Minimal contour-focused style emphasizing crisp outlines, simplified shading, and uncluttered visual hierarchy.',
        'instruction': 'Prioritize clean line structure, simplified shading, intentional contour placement, and strong silhouette separation. Keep each outline purposeful, spacing disciplined, and noise minimal so the image reads immediately with precise graphic clarity.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'manga_ink',
        'label': 'Manga Ink [manga] [ink]',
        'tags': ['manga', 'ink'],
        'description': 'Ink-first manga aesthetic with decisive blacks, controlled hatch textures, screentone logic, and dramatic value contrast.',
        'instruction': 'Render with confident manga ink lines, clean black massing, selective screentone or hatch texture, and deliberate contrast for strong panel readability. Keep character expression, perspective, and light-dark rhythm crisp and graphic without muddy grayscale rendering.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'mascot_illustration',
        'label': 'Mascot Illustration [illustration] [branding]',
        'tags': ['illustration', 'branding'],
        'description': 'Mascot-illustration style with strong silhouette, expressive appeal, and brand-friendly character clarity.',
        'instruction': 'Render as a mascot illustration with memorable shape language, strong facial readability, simplified but expressive anatomy, and bold brand-friendly presence. Preserve instant recognizability and clean graphic appeal without over-rendering or visual clutter.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'mecha_illustration',
        'label': 'Mecha Illustration [illustration] [scifi]',
        'tags': ['illustration', 'scifi'],
        'description': 'Mecha-illustration style with mechanical silhouette logic, panel readability, and dynamic futuristic design clarity.',
        'instruction': 'Render as mecha illustration with strong mechanical structure, purposeful silhouette design, readable joints and paneling, and clean high-impact composition. Preserve technical logic and visual power without descending into unreadable over-detailing.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'retro_cartoon_illustration',
        'label': 'Retro Cartoon Illustration [illustration] [vintage]',
        'tags': ['illustration', 'vintage'],
        'description': 'Retro-cartoon style with vintage shape language, graphic color separation, and era-inspired character charm.',
        'instruction': 'Render as a retro cartoon illustration with period-inspired design language, strong contour shapes, restrained palette logic, and playful vintage character appeal. Preserve era flavor and graphic readability without muddying the style with modern over-rendering.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'pastel_illustration',
        'label': 'Soft Pastel Illustration [illustration] [pastel]',
        'tags': ['illustration', 'pastel'],
        'description': 'Soft pastel treatment with gentle saturation, matte tonality, airy layering, and calm visual softness.',
        'instruction': 'Use restrained color intensity, soft edges, powdery texture cues, and airy tonal layering to keep the scene calm, elegant, and easy to parse. Preserve shape clarity and compositional order while maintaining the softness of the medium.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'sticker_pack_illustration',
        'label': 'Sticker Pack Illustration [illustration] [graphic]',
        'tags': ['illustration', 'graphic'],
        'description': 'Sticker-pack illustration style with bold outlines, compact compositions, and merch-ready character or object readability.',
        'instruction': "Render as a sticker-pack illustration with strong silhouette shapes, clear contour definition, simple color grouping, and small-format readability. Preserve each design's individuality and cutout-friendliness without unnecessary fine detail.",
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'storybook_illustration',
        'label': 'Storybook Illustration [illustration] [storybook]',
        'tags': ['illustration', 'storybook'],
        'description': 'Narrative storybook style with warm color design, approachable detail, expressive charm, and page-friendly scene readability.',
        'instruction': 'Render as storybook illustration with inviting composition, expressive character readability, soft-but-structured detail, and a cohesive narrative atmosphere. Preserve warmth, charm, and visual flow without drifting into generic cartoon clutter.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'surreal_editorial',
        'label': 'Surreal Editorial [editorial] [surreal]',
        'tags': ['editorial', 'surreal'],
        'description': 'Stylized surreal-editorial look balancing fashion or design polish with dreamlike logic, symbolic composition, and controlled visual strangeness.',
        'instruction': 'Use surreal editorial treatment with clean composition, polished stylization, and impossible or symbolic elements integrated in a coherent way. Keep the imagery visually intentional, readable, and high-concept rather than random or chaotic.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'urban_semi_realism',
        'label': 'Urban Semi-Realism [urban] [semi-realism]',
        'tags': ['urban', 'semi-realism'],
        'description': 'Modern city-inspired semi-realistic look balancing believable materials, stylized clarity, and editorial street-image polish.',
        'instruction': 'Apply urban semi-realism with realistic structure and stylized polish: clean edges, disciplined textures, mild color grading, believable materials, and modern street-scene readability. Keep the result contemporary, grounded, and visually sharp without drifting into either flat cartooning or overcooked realism.',
        'main_category': 'Illustration / 2D Stylized',
    },
    {
        'key': 'vector_flat_illustration',
        'label': 'Vector Flat Illustration [vector] [illustration]',
        'tags': ['vector', 'illustration'],
        'description': 'Clean flat-vector illustration with simplified geometric forms, disciplined color blocking, and scalable design clarity.',
        'instruction': 'Render as flat vector illustration with crisp edges, minimal shading, strong shape simplification, and balanced negative space. Keep the composition clean, icon-friendly, and scalable without painterly texture or raster-style noise.',
        'main_category': 'Illustration / 2D Stylized',
    },
]
