from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'acrylic_painting',
        'label': 'Acrylic Painting [painting] [traditional]',
        'tags': ['painting', 'traditional'],
        'description': 'Acrylic painting style with bold color, layered brush texture, and crisp painterly edge control.',
        'instruction': 'Use acrylic paint behavior with opaque layering, visible brush direction, strong local color, and sharper transitions than watercolor or oil. Preserve painterly energy and medium texture while keeping composition and subject readability strong.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'chalk_pastel',
        'label': 'Chalk Pastel Drawing [drawing] [traditional]',
        'tags': ['drawing', 'traditional'],
        'description': 'Chalk-pastel style with powdery edges, soft blending, bold mark texture, and tactile color massing.',
        'instruction': 'Render with chalk-pastel logic using dusty texture, layered soft blending, and visible mark variation. Preserve medium grain, expressive color massing, and hand-worked texture while maintaining subject clarity.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'charcoal_drawing',
        'label': 'Charcoal Drawing [traditional] [drawing]',
        'tags': ['traditional', 'drawing'],
        'description': 'Expressive charcoal drawing with dusty texture, bold tonal massing, tactile paper tooth, and hand-drawn contrast.',
        'instruction': 'Render with charcoal logic: soft smudged transitions, strong dark massing, visible paper texture, and selective edge refinement. Preserve gesture, material grit, and structural value design without over-cleaning the handmade character.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'colored_pencil',
        'label': 'Colored Pencil Illustration [drawing] [traditional]',
        'tags': ['drawing', 'traditional'],
        'description': 'Colored-pencil style with layered strokes, grain-sensitive shading, and gentle hand-rendered color buildup.',
        'instruction': 'Use colored-pencil rendering with visible stroke layering, paper texture interaction, and gradual tonal buildup. Keep the result tactile, illustrative, and controlled rather than overly smooth or digitally airbrushed.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'fantasy_painting',
        'label': 'Fantasy Painting [painting] [fantasy]',
        'tags': ['painting', 'fantasy'],
        'description': 'Epic fantasy painting style with atmospheric depth, dramatic scale cues, rich world-building detail, and painterly grandeur.',
        'instruction': 'Use fantasy-art painting treatment with strong focal composition, layered environment depth, dramatic lighting, and deliberate material contrast. Preserve mythic atmosphere and imaginative scale while keeping the scene readable and compositionally controlled.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'gouache_painting',
        'label': 'Gouache Painting [painting] [traditional]',
        'tags': ['painting', 'traditional'],
        'description': 'Opaque gouache painting style with matte surface character, simplified shapes, and bold but controlled color blocking.',
        'instruction': 'Render with gouache logic using flattened opaque paint layers, softly textured brush edges, strong shape simplification, and balanced color relationships. Keep the result tactile, graphic, and painterly without glossy oil-like blending.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'ink_wash',
        'label': 'Ink Wash Illustration [traditional] [ink]',
        'tags': ['traditional', 'ink'],
        'description': 'Ink-wash style combining controlled brush line, fluid tonal wash, organic bleed, and elegant negative-space balance.',
        'instruction': 'Use brush-ink linework with diluted wash values, soft bleed behavior, and strong light-dark simplification. Keep the result breathable, elegant, and compositionally balanced rather than overworked or texture-heavy.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'linocut_print_style',
        'label': 'Linocut Print Style [printmaking] [traditional]',
        'tags': ['printmaking', 'traditional'],
        'description': 'Linocut-print style with bold carved contours, simplified shapes, and graphic hand-printed contrast.',
        'instruction': 'Render as a linocut print with simplified carved marks, strong positive-negative shape logic, and tactile print imperfections. Preserve hand-cut clarity and printmaking rhythm rather than polished digital smoothness.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'matte_painting',
        'label': 'Matte Painting [painting] [environment]',
        'tags': ['painting', 'environment'],
        'description': 'Cinematic matte-painting style with large-scale environment design, atmospheric depth, and production-ready compositional clarity.',
        'instruction': 'Use matte-painting logic with layered environment depth, strong horizon or scale cues, controlled atmospheric perspective, and selective detail in focal regions. Preserve cinematic believability and environment storytelling without over-filling every surface.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'oil_painting',
        'label': 'Oil Painting [painting] [traditional]',
        'tags': ['painting', 'traditional'],
        'description': 'Rich painterly treatment with visible brushwork, blended tonal transitions, tactile color depth, and classical surface presence.',
        'instruction': 'Use confident brushstroke rhythm, layered paint texture, and controlled color temperature contrast. Keep focal zones sharper and peripheral zones more suggestive, with believable paint handling, depth-rich color, and a strong hierarchy of detail.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'pencil_sketch',
        'label': 'Pencil Sketch [drawing] [traditional]',
        'tags': ['drawing', 'traditional'],
        'description': 'Graphite-sketch style with line sensitivity, tonal shading, and draftsmanship-focused structure.',
        'instruction': 'Render as a pencil sketch with clean line weight variation, graphite shading, visible construction confidence, and paper-based tonal softness. Preserve hand-drawn structure and sketch character without turning it into polished ink art.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'ukiyo_e',
        'label': 'Ukiyo-e Print Style [printmaking] [traditional]',
        'tags': ['printmaking', 'traditional'],
        'description': 'Woodblock-print-inspired style with flat color planes, elegant line rhythm, and stylized compositional balance.',
        'instruction': 'Use ukiyo-e-inspired visual logic with controlled outlines, flattened perspective cues, patterned surfaces, and disciplined color separation. Preserve print-like simplicity, rhythmic composition, and decorative balance without modern over-rendering.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'watercolor',
        'label': 'Watercolor Painting [painting] [traditional]',
        'tags': ['painting', 'traditional'],
        'description': 'Soft watercolor wash behavior with gentle pigment bleed, paper grain, translucent layering, and organic tonal softness.',
        'instruction': 'Apply translucent washes, edge bloom, pigment granulation, and paper texture interaction. Preserve organic imperfections, delicate layering, and soft transitions while maintaining value structure, subject clarity, and readable composition.',
        'main_category': 'Painting / Traditional Media',
    },
    {
        'key': 'woodcut_print_style',
        'label': 'Woodcut Print Style [printmaking] [traditional]',
        'tags': ['printmaking', 'traditional'],
        'description': 'Woodcut-print style with carved line rhythm, strong black shapes, and tactile hand-pressed print character.',
        'instruction': 'Render as a woodcut print with carved mark texture, bold contrast, visible cut-line direction, and handmade printing irregularities. Preserve the block-printed feel and high-contrast graphic structure instead of smooth illustration rendering.',
        'main_category': 'Painting / Traditional Media',
    },
]
