from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'pbr_albedo_map',
        'label': '3D Albedo/Base Color Map [map] [pbr]',
        'tags': ['map', 'pbr'],
        'description': 'Texture-map style for pure base-color output without baked lighting, AO, reflections, or shading gradients.',
        'instruction': 'Generate a clean albedo or base-color map only. Exclude shadows, highlights, AO, emission, and normal detail; keep colors flat, material-separated, texture-consistent, and tile-safe for production workflows.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_ao_map',
        'label': '3D Ambient Occlusion Map [map] [pbr]',
        'tags': ['map', 'pbr'],
        'description': 'Ambient occlusion map style emphasizing contact-shadow cavities and crevice density independent of direct lighting direction.',
        'instruction': 'Generate an AO map focused on crevices, cavities, overlaps, and contact zones only. Keep it grayscale, smooth, and free of directional light bias, material color contamination, or dramatic artistic shadowing.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_curvature_map',
        'label': '3D Curvature Map [map] [mask]',
        'tags': ['map', 'mask'],
        'description': 'Curvature map style emphasizing convex and concave edge behavior for wear, edge-mask, and procedural texturing workflows.',
        'instruction': 'Generate a curvature map that clearly differentiates convex ridges, concave cavities, and edge transitions. Keep the result technically clean, high-signal, and suitable for downstream masking rather than artistic rendering.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_emissive_map',
        'label': '3D Emissive Map [map] [pbr]',
        'tags': ['map', 'pbr'],
        'description': 'Emissive-mask style isolating self-illuminating regions for glow-capable materials with clean production boundaries.',
        'instruction': 'Output an emissive map that isolates luminous regions only. Keep non-emissive areas dark, boundaries clean, and intensity zones production-ready without shading contamination or albedo detail.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_height_map',
        'label': '3D Height/Displacement Map [map] [pbr]',
        'tags': ['map', 'pbr'],
        'description': 'Height-map style encoding elevation detail for displacement or parallax workflows with stable depth hierarchy.',
        'instruction': 'Produce a grayscale height map with clear elevation hierarchy, smooth gradients, and physically coherent depth intent. Avoid lighting artifacts, color information, or noisy surface confusion that weakens displacement readability.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_material_id_map',
        'label': '3D Material ID Map [map] [mask]',
        'tags': ['map', 'mask'],
        'description': 'Material-ID mask style assigning flat, distinct colors to material regions for clean texturing workflow control.',
        'instruction': 'Produce a material-ID map with clean, non-anti-aliased region boundaries and unique flat colors per material zone. Exclude gradients, shading, and decorative noise so each material region remains unmistakably separable.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_metallic_map',
        'label': '3D Metallic Map [map] [pbr]',
        'tags': ['map', 'pbr'],
        'description': 'Metalness map style separating dielectric and conductive regions with crisp material-mask clarity.',
        'instruction': 'Create a metallic map with clean dielectric-versus-metal separation and crisp material regions. Avoid painted lighting, soft ambiguity, or texture noise that would weaken downstream PBR control.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_normal_map',
        'label': '3D Normal Map [map] [pbr]',
        'tags': ['map', 'pbr'],
        'description': 'Tangent-space normal map style with clear surface-direction encoding, smooth gradients, and no albedo contamination.',
        'instruction': 'Generate a proper tangent-space normal map with coherent RGB directional encoding, smooth gradient continuity, and no baked lighting or color texture data. Keep surface transitions technically readable and artifact-free.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_opacity_map',
        'label': '3D Opacity/Alpha Map [map] [pbr]',
        'tags': ['map', 'pbr'],
        'description': 'Alpha-opacity map style defining transparency coverage with clean mask control and production-friendly edge handling.',
        'instruction': 'Create an opacity or alpha map with clear opaque-to-transparent control, anti-aliased edge quality where needed, and no shading contamination. Prioritize crisp transparency logic that is directly usable in material workflows.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_roughness_map',
        'label': '3D Roughness Map [map] [pbr]',
        'tags': ['map', 'pbr'],
        'description': 'Grayscale roughness map style encoding microsurface scatter from glossy to matte with stable material separation.',
        'instruction': 'Generate a roughness map in grayscale where dark values are smoother or glossier and bright values are rougher or more matte. Keep transitions material-faithful, stable, and free of lighting artifacts or decorative shading.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_specular_gloss_map',
        'label': '3D Specular/Glossiness Map [map] [pbr]',
        'tags': ['map', 'pbr'],
        'description': 'Specular-glossiness workflow map style controlling reflective intensity and highlight tightness with stable grayscale logic.',
        'instruction': 'Generate a specular or glossiness map suitable for spec-gloss pipelines, with stable grayscale values, material-faithful contrast, and no baked directional light cues. Keep the data technically readable and pipeline-safe.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_uv_layout',
        'label': '3D UV Layout Map [map] [uv]',
        'tags': ['map', 'uv'],
        'description': 'UV layout style showing shell boundaries, seam structure, and packing clarity for texture-workflow verification.',
        'instruction': 'Output a UV layout map with clear island boundaries, seam visibility, readable packing, and strong technical legibility. Focus on UV structure and organization, not shading or material rendering.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
    {
        'key': 'pbr_wireframe_topology',
        'label': '3D Wireframe Topology [map] [wireframe]',
        'tags': ['map', 'wireframe'],
        'description': 'Wireframe-topology visualization style showing edge flow, polygon density, and mesh readability for technical inspection.',
        'instruction': 'Render a wireframe topology view with clear edge flow, consistent line thickness, readable polygon distribution, and strong technical legibility. Focus on topology communication, not material shading or cinematic presentation.',
        'main_category': 'PBR / Texture / Map Outputs',
    },
]
