from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'architectural_photo',
        'label': 'Architectural Photograph [photo] [architecture]',
        'tags': ['photo', 'architecture'],
        'description': 'Architecture-focused photography with disciplined perspective, clean line control, material readability, and strong spatial clarity.',
        'instruction': 'Maintain straight-line integrity, coherent vanishing geometry, realistic scale cues, and lighting that reveals form without flattening depth. Preserve facade rhythm, interior-exterior balance, and architectural intent while avoiding warped perspective or excessive stylistic distortion.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'automotive_photo',
        'label': 'Automotive Photography [photo] [automotive]',
        'tags': ['photo', 'automotive'],
        'description': 'Automotive-photo style with sculpted reflections, body-line emphasis, and performance-forward commercial polish.',
        'instruction': 'Render as high-end automotive photography with controlled reflections, paint-finish clarity, wheel and body-line readability, and lighting that accentuates form and engineering detail. Keep the vehicle dominant and visually powerful without showroom clutter.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'beauty_photography',
        'label': 'Beauty Photography [photo] [beauty]',
        'tags': ['photo', 'beauty'],
        'description': 'Beauty-photo style with skin-detail control, refined cosmetic emphasis, and clean premium lighting.',
        'instruction': 'Treat this as beauty photography with careful light shaping, crisp cosmetic detail, refined skin rendering, and strong facial focal clarity. Preserve realism and polish without plastic retouching or artificial over-smoothing.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'black_and_white_photo',
        'label': 'Black and White Photograph [photo] [monochrome]',
        'tags': ['photo', 'monochrome'],
        'description': 'Monochrome photo treatment emphasizing tonal contrast, texture definition, light shaping, and dramatic grayscale discipline.',
        'instruction': 'Use black-and-white photography discipline with deep tonal range, strong subject separation, rich midtone control, and intentional highlight-shadow balance. Preserve material texture and grayscale clarity with no color contamination or fake tinting.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'cinematic_still',
        'label': 'Cinematic Still [cinematic] [lighting]',
        'tags': ['cinematic', 'lighting'],
        'description': 'Film-like framing with layered depth, intentional contrast, controlled atmosphere, and strong single-frame storytelling clarity.',
        'instruction': 'Stage this as a cinematic still with strong composition, clear focal hierarchy, motivated key/fill/rim lighting, controlled atmosphere, and deliberate foreground-to-background separation. Keep the storytelling readable in a single frame, with restrained grading and visually meaningful production detail rather than empty cinematic buzzwords.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'corporate_portrait',
        'label': 'Corporate Portrait [photo] [business]',
        'tags': ['photo', 'business'],
        'description': 'Corporate-portrait style with professional confidence, clean lighting, and business-ready presentation polish.',
        'instruction': 'Render as a corporate portrait with controlled flattering light, clean wardrobe or role-appropriate presentation, and polished but realistic business photography discipline. Preserve professionalism, strong eye contact, and subject clarity without fashion-editorial excess.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'documentary_photo',
        'label': 'Documentary Photograph [photo] [documentary]',
        'tags': ['photo', 'documentary'],
        'description': 'Observational documentary photo style with candid realism, natural light behavior, situational texture, and unforced authenticity.',
        'instruction': 'Render as documentary photography with truthful framing, realistic available light, lived-in imperfection, and emotionally credible moment capture. Preserve authenticity and contextual detail without excessive glamour, retouching, or staged commercial polish.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'editorial_portrait_photo',
        'label': 'Editorial Portrait [photo] [portrait]',
        'tags': ['photo', 'portrait'],
        'description': 'Magazine-style portrait photography with strong subject presence, controlled lighting, and refined visual polish.',
        'instruction': 'Treat this as editorial portrait photography with clear subject priority, flattering but intentional light shaping, controlled background separation, and premium tonal polish. Preserve expression, skin texture, and pose readability without beauty-filter artificiality.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'event_photography',
        'label': 'Event Photography [photo] [event]',
        'tags': ['photo', 'event'],
        'description': 'Event-photography style with candid moment capture, crowd awareness, and polished documentary realism.',
        'instruction': 'Render as event photography with natural timing, believable ambient light handling, and clear capture of atmosphere, people, and key moments. Preserve candid realism and event energy without staged portrait stiffness or muddled crowd chaos.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'fashion_editorial',
        'label': 'Fashion Editorial [photo] [editorial]',
        'tags': ['photo', 'editorial'],
        'description': 'High-end fashion editorial look with confident pose language, directional lighting, styling-forward composition, and magazine-ready toning.',
        'instruction': 'Treat this as fashion editorial photography with intentional pose design, wardrobe emphasis, refined lighting contrast, and premium print-grade color control. Preserve garment readability, body-line elegance, and campaign-level polish while avoiding generic glamour clutter or over-retouched skin.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'fine_art_portrait',
        'label': 'Fine Art Portrait [photo] [fine-art]',
        'tags': ['photo', 'fine-art'],
        'description': 'Fine-art portrait style with deliberate composition, sculpted lighting, restrained palette, and emotionally focused atmosphere.',
        'instruction': 'Render as fine-art portraiture with carefully shaped light, strong compositional intention, tactile tonal control, and psychologically readable mood. Keep the result elegant, emotionally grounded, and visually disciplined rather than over-stylized.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'flat_lay_product_photo',
        'label': 'Flat Lay Product Photo [photo] [product]',
        'tags': ['photo', 'product'],
        'description': 'Top-down product photography style with clean layout geometry, controlled shadows, and commerce-friendly visual organization.',
        'instruction': 'Treat this as professional flat-lay photography with overhead composition, disciplined spacing, clean background control, and balanced studio lighting. Preserve product readability and arrangement clarity without lifestyle clutter or distracting perspective distortion.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'food_photography',
        'label': 'Food Photography [photo] [food]',
        'tags': ['photo', 'food'],
        'description': 'Appetite-driven culinary photo style with texture-rich close detail, appetizing light control, and premium plating readability.',
        'instruction': 'Apply professional food styling with realistic garnish control, fresh surface highlights, appetizing moisture or steam cues where relevant, and composition that emphasizes texture, freshness, and plating. Avoid artificial plastic sheen, cluttered tablescapes, or muddy color that reduces appetite appeal.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'headshot_photography',
        'label': 'Headshot Photography [photo] [portrait]',
        'tags': ['photo', 'portrait'],
        'description': 'Professional headshot-photography style with flattering lighting, clean framing, and polished subject-forward clarity.',
        'instruction': 'Render as a professional headshot with controlled portrait lighting, flattering but realistic skin rendering, clean background separation, and strong facial focus. Preserve confidence, readability, and subtle polish without excessive glamour retouching or cinematic distraction.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'lifestyle_product_photography',
        'label': 'Lifestyle Product Photography [photo] [commercial]',
        'tags': ['photo', 'commercial'],
        'description': 'Lifestyle product-photo style with aspirational context, natural usage storytelling, and premium commercial polish.',
        'instruction': 'Render as lifestyle product photography with believable contextual props, practical lighting, and strong product visibility inside a lived-in scene. Preserve commercial clarity and desirability while avoiding clutter or losing the product as the focal point.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'long_exposure_photography',
        'label': 'Long Exposure Photography [photo] [specialty]',
        'tags': ['photo', 'specialty'],
        'description': 'Long-exposure style with motion trails, temporal blur effects, and controlled photographic realism.',
        'instruction': 'Render as long-exposure photography with believable motion streaks, light trails, water or cloud smoothing where appropriate, and stable exposure logic. Preserve photographic realism and compositional clarity rather than generic motion-blur chaos.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'macro_photo',
        'label': 'Macro Photograph [photo] [macro]',
        'tags': ['photo', 'macro'],
        'description': 'Close-focus macro style emphasizing micro texture, shallow depth, optical realism, and fine detail at the focus plane.',
        'instruction': 'Use macro lens behavior with narrow depth of field, crisp local detail at the focus plane, realistic bokeh falloff, and believable surface scale. Preserve subject structure and texture while avoiding fake oversharpening or impossible depth behavior.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'maternity_photography',
        'label': 'Maternity Photography [photo] [portrait]',
        'tags': ['photo', 'portrait'],
        'description': 'Maternity-portrait style with gentle light, respectful composition, and warm intimate subject focus.',
        'instruction': 'Render as maternity photography with flattering soft light, respectful body framing, and emotionally warm presentation. Preserve realism, dignity, and calm intimacy without fashion-editorial excess or over-stylized retouching.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'night_photography',
        'label': 'Night Photography [photo] [lighting]',
        'tags': ['photo', 'lighting'],
        'description': 'Night-photo style with low-light realism, strong practical-light hierarchy, and controlled dark-scene readability.',
        'instruction': 'Render as night photography with believable low-light exposure, practical light sources, deep but readable shadows, and coherent color temperature interplay. Preserve atmosphere and realism without crushing detail into black or oversaturating artificial light.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'noir',
        'label': 'Noir Film Style [cinematic] [monochrome]',
        'tags': ['cinematic', 'monochrome'],
        'description': 'Classic noir mood using high-contrast chiaroscuro, hard shadow geometry, atmospheric depth, and unmistakable narrative tension.',
        'instruction': 'Push noir lighting structure with directional shadows, selective highlights, deep blacks, and moody spatial layering. Keep silhouettes, reflective surfaces, smoke or haze cues, and narrative intent unmistakable without turning the frame into unreadable darkness.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'pet_photography',
        'label': 'Pet Photography [photo] [animal]',
        'tags': ['photo', 'animal'],
        'description': 'Pet-photography style with animal personality, fur-detail clarity, and warm commercial or personal realism.',
        'instruction': 'Render as pet photography with strong focus on animal expression, posture, fur texture, and clean scene readability. Preserve natural charm and believable behavior without anthropomorphic distortion or busy distracting backgrounds.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'photograph_real_life',
        'label': 'Photograph (Real Life) [photo] [real-life]',
        'tags': ['photo', 'real-life'],
        'description': 'Natural real-life photography with believable texture, practical lighting, authentic lens behavior, and grounded everyday realism.',
        'instruction': 'Render as a grounded real-life photograph using coherent lens behavior, real-life exposure, physically plausible material response, and natural environmental imperfection. Preserve authentic skin, fabric, surfaces, and lighting falloff; avoid synthetic gloss, exaggerated stylization, artificial HDR, or game-like rendering artifacts.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'photorealistic_render',
        'label': 'Photorealistic Render [photo] [realism]',
        'tags': ['photo', 'realism'],
        'description': 'High-fidelity realism with sharp material definition, lifelike surfaces, stable dynamic range, and convincing real-world optical behavior.',
        'instruction': 'Use a photorealistic treatment with accurate microdetail, natural focus falloff, stable highlight rolloff, and physically coherent texture response. Preserve true-to-life color, realistic surface roughness, and believable depth while avoiding over-sharpening, plastic skin, waxy materials, or over-processed rendering artifacts.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'sepia_photo',
        'label': 'Sepia Photograph [photo] [vintage]',
        'tags': ['photo', 'vintage'],
        'description': 'Warm sepia vintage look with archival tonality, subtle grain, aged photographic warmth, and restrained contrast.',
        'instruction': 'Apply sepia toning with gentle age cues, mild grain, softened tonal response, and period-like photographic character. Keep the image readable and authentic-looking while avoiding excessive scratches, fake distressing, or novelty aging effects.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'sports_action_photo',
        'label': 'Sports Action Photo [photo] [sports]',
        'tags': ['photo', 'sports'],
        'description': 'Dynamic sports-photography style with peak-action timing, motion clarity, and high-energy subject isolation.',
        'instruction': 'Treat this as sports action photography with decisive timing, readable body mechanics, clear motion emphasis, and strong separation between athlete and environment. Preserve intensity and realism without confusing blur or chaotic framing.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'street_photography',
        'label': 'Street Photography [photo] [street]',
        'tags': ['photo', 'street'],
        'description': 'Candid street-photo style with spontaneous timing, lived-in urban texture, and documentary realism.',
        'instruction': 'Render as street photography with natural timing, observational framing, environmental context, and believable available light. Preserve candid energy, human scale, and city texture without commercial polish or overly staged posing.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'studio_product_photo',
        'label': 'Studio Product Photograph [photo] [product]',
        'tags': ['photo', 'product'],
        'description': 'Commercial studio product photo style with controlled reflections, pristine background handling, premium edge separation, and catalog-grade sharpness.',
        'instruction': 'Treat this as premium product photography with clean set lighting, precise reflection management, material-accurate highlights, and uncluttered composition suitable for commerce. Preserve brand-neutral polish, balanced grounding shadows, and premium commercial readability without unnecessary props or lifestyle clutter.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'travel_photography',
        'label': 'Travel Photography [photo] [travel]',
        'tags': ['photo', 'travel'],
        'description': 'Travel-photo style with location-rich atmosphere, clear sense of place, and inviting visual storytelling.',
        'instruction': 'Treat this as travel photography with strong environmental context, honest light, and a vivid sense of place. Preserve cultural or geographic specificity, spatial depth, and discoverable detail without turning the scene into generic postcard cliché.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'underwater_photography',
        'label': 'Underwater Photography [photo] [specialty]',
        'tags': ['photo', 'specialty'],
        'description': 'Underwater-photo style with aquatic light behavior, suspended atmosphere, and believable submerged realism.',
        'instruction': 'Render as underwater photography with realistic light diffusion, water color absorption, suspended particles, and believable motion or buoyancy cues. Preserve aquatic realism and optical clarity without turning the scene into fantasy glow effects.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'wedding_photography',
        'label': 'Wedding Photography [photo] [wedding]',
        'tags': ['photo', 'wedding'],
        'description': 'Wedding-photo style with emotional moment focus, flattering light, and premium celebration realism.',
        'instruction': 'Render as wedding photography with elegant composition, soft flattering light, strong emotional clarity, and clean moment storytelling. Preserve romance, documentary honesty, and premium polish without heavy artificial glamour processing.',
        'main_category': 'Photography / Realism',
    },
    {
        'key': 'wildlife_photography',
        'label': 'Wildlife Photography [photo] [wildlife]',
        'tags': ['photo', 'wildlife'],
        'description': 'Wildlife-photo style with natural animal behavior, environmental realism, and long-lens observational clarity.',
        'instruction': 'Render as wildlife photography with believable animal posture, habitat context, realistic fur or feather texture, and natural light behavior. Preserve observational authenticity and subject respect without anthropomorphic stylization or fake studio polish.',
        'main_category': 'Photography / Realism',
    },
]
