from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'baby_birth_announcement',
        'label': 'Baby Birth Announcement [event] [card]',
        'tags': ['event', 'card'],
        'description': 'Birth-announcement card style with gentle hierarchy, keepsake presentation, and warm personal readability.',
        'instruction': 'Design as a baby birth announcement with a clear focal message, balanced typography, and soft celebratory presentation. Preserve keepsake-card polish and readable detail placement without crowding the small format.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'baby_shower_flyer',
        'label': 'Baby Shower Flyer [design] [event]',
        'tags': ['design', 'event', 'flyer', 'print'],
        'description': 'Celebratory baby-shower flyer style with warm welcoming tone, soft event-friendly layout, and clear invitation readability.',
        'instruction': 'Design as a baby shower flyer with inviting composition, clear event hierarchy, readable date-time-location placement, and a warm celebratory tone. Use gentle visual rhythm, polished typography, and a balanced decorative approach that supports readability first. Keep the design print-friendly, charming, and organized without overcrowding the page or sacrificing essential event information.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'birthday_invite',
        'label': 'Birthday Invitation / RSVP [design] [event]',
        'tags': ['design', 'event', 'invite', 'rsvp'],
        'description': 'Birthday invitation style with festive visual energy, clear RSVP structure, and strong event-information readability.',
        'instruction': 'Design as a birthday invitation or RSVP card with celebratory tone, clear headline hierarchy, readable event details, and a polished invitation layout. Preserve strong visual appeal, easy-to-scan structure, and enough negative space for names, dates, location, RSVP information, and optional theme elements. Keep the result festive and well-organized rather than chaotic or overdecorated.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'bridal_shower_invite',
        'label': 'Bridal Shower Invite [event] [invite]',
        'tags': ['event', 'invite'],
        'description': 'Bridal-shower invitation style with celebratory elegance, soft event hierarchy, and polished invitation readability.',
        'instruction': 'Design as a bridal shower invitation with welcoming composition, strong event-detail hierarchy, and tasteful decorative softness. Preserve celebratory elegance, print-ready clarity, and balanced spacing without visual clutter.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'brochure_design',
        'label': 'Brochure Design [design] [print]',
        'tags': ['design', 'print', 'brochure', 'marketing'],
        'description': 'Professional brochure style with structured information hierarchy, premium layout rhythm, and print-ready editorial clarity.',
        'instruction': 'Design as a brochure with clear sectioning, disciplined grid logic, readable typography hierarchy, and polished marketing presentation. Preserve print-friendly spacing, fold-aware organization, and balanced imagery-text relationships without turning the layout into dense clutter.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'business_card_design',
        'label': 'Business Card Design [design] [branding]',
        'tags': ['design', 'branding', 'print', 'business-card'],
        'description': 'Professional business-card design style with clear hierarchy, brand polish, print-ready layout discipline, and strong small-format readability.',
        'instruction': 'Design as a professional business card with disciplined spacing, strong typographic hierarchy, clean logo placement, and print-aware composition. Preserve readability at small scale, clear contact-detail zones, strong brand alignment, and premium visual polish. Keep the result uncluttered, production-friendly, and suitable for front-and-back card use rather than poster-like or decorative layout excess.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'calendar_design',
        'label': 'Calendar Layout [design] [document]',
        'tags': ['design', 'document', 'calendar', 'print'],
        'description': 'Calendar design style with structured date-grid readability, balanced page rhythm, and functional scheduling clarity.',
        'instruction': 'Design as a calendar layout with readable date hierarchy, clean grid structure, balanced spacing, and practical planning usability. Preserve clear month or schedule organization without excessive decorative noise that hurts legibility.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'certificate_design',
        'label': 'Certificate Design [design] [formal]',
        'tags': ['design', 'formal', 'certificate', 'print'],
        'description': 'Formal certificate style with institutional hierarchy, refined ornament restraint, and premium document presentation.',
        'instruction': 'Design as a professional certificate with strong title hierarchy, signature and seal zones, balanced margins, and formal polished composition. Preserve elegance, legitimacy, and print-readiness while avoiding clutter or overly novelty styling.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'coupon_design',
        'label': 'Coupon / Promo Voucher [design] [marketing]',
        'tags': ['design', 'marketing', 'coupon', 'print'],
        'description': 'Promotional coupon style with strong offer hierarchy, redemption clarity, and clean retail-ready layout.',
        'instruction': 'Design as a coupon or promo voucher with bold offer emphasis, clear terms area, readable call-to-action, and practical layout structure. Preserve immediate value communication, visual punch, and redemption usability without clutter or tiny unreadable legal-style detail dominating the design.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'event_ticket_design',
        'label': 'Event Ticket Design [event] [print]',
        'tags': ['event', 'print'],
        'description': 'Event-ticket style with compact information hierarchy, collectible appeal, and print-friendly layout clarity.',
        'instruction': 'Design as an event ticket with strong event branding, readable seat/date/location details, and compact format organization. Preserve both practical usability and collectible-style visual appeal without overloading the ticket with too much noise.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'flyer_design',
        'label': 'Flyer Design [design] [print]',
        'tags': ['design', 'print', 'flyer', 'marketing'],
        'description': 'High-clarity flyer design style with strong hierarchy, fast scanability, and effective print or digital handout impact.',
        'instruction': 'Design as a professional flyer with clear visual hierarchy, strong headline treatment, organized supporting sections, and highly readable information flow. Preserve print-ready spacing, immediate communication impact, and strong callout structure without overcrowding or collapsing into poster-noise.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'funeral_memorial_program',
        'label': 'Funeral / Memorial Program [event] [print]',
        'tags': ['event', 'print'],
        'description': 'Memorial-program style with respectful typography, calm layout, and dignified printed-document clarity.',
        'instruction': 'Design as a funeral or memorial program with gentle visual restraint, clear service hierarchy, readable information structure, and dignified presentation. Preserve solemnity, calm, and print-readiness without decorative excess.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'gift_certificate_design',
        'label': 'Gift Certificate [design] [business]',
        'tags': ['design', 'business', 'certificate', 'gift-card'],
        'description': 'Gift-certificate style with premium promotional clarity, elegant balance, and clean business-ready layout.',
        'instruction': 'Design as a gift certificate with clear value or offer emphasis, polished branding, elegant spacing, and readable recipient and redemption zones. Preserve premium presentation and practical usability without looking like a crowded flyer.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'graduation_announcement',
        'label': 'Graduation Announcement [event] [card]',
        'tags': ['event', 'card'],
        'description': 'Graduation-announcement style with achievement-forward hierarchy, polished stationery composition, and keepsake readability.',
        'instruction': 'Design as a graduation announcement with strong name/date hierarchy, celebratory polish, and clear announcement structure. Preserve premium card-like presentation and clean readability rather than flyer-style crowding.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'greeting_card_design',
        'label': 'Greeting Card [design] [stationery]',
        'tags': ['design', 'stationery', 'card', 'print'],
        'description': 'Versatile greeting-card style with strong front-panel focal design, readable message hierarchy, and polished printable layout.',
        'instruction': 'Design as a greeting card with a memorable cover composition, clear message hierarchy, and balanced decorative treatment. Preserve clean typography, strong focal imagery, and print-friendly spacing so the result feels like a finished retail or custom card rather than a poster reduced in size.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'holiday_party_invite',
        'label': 'Holiday Party Invite [event] [invite]',
        'tags': ['event', 'invite'],
        'description': 'Holiday-party invitation style with festive hierarchy, seasonal visual warmth, and readable event structure.',
        'instruction': 'Design as a holiday party invitation with celebratory energy, strong event-detail hierarchy, and polished invitation layout. Preserve festive tone and readability while avoiding overcrowding or novelty clutter.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'letterhead_design',
        'label': 'Letterhead Design [design] [business]',
        'tags': ['design', 'business', 'stationery', 'letterhead'],
        'description': 'Corporate letterhead style with restrained branding, document clarity, and premium professional stationery polish.',
        'instruction': 'Design as a business letterhead with restrained brand placement, clean margin logic, readable content space, and polished stationery presentation. Preserve professional tone and document usability without overpowering the page with graphics.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'menu_design',
        'label': 'Menu Design [design] [restaurant]',
        'tags': ['design', 'restaurant', 'menu', 'print'],
        'description': 'Restaurant-menu style with category clarity, readable pricing structure, and polished hospitality-focused layout.',
        'instruction': 'Design as a restaurant or service menu with strong category hierarchy, readable item grouping, clear pricing alignment, and polished presentation. Preserve easy scanning, balanced spacing, and premium visual rhythm while avoiding clutter, tiny type, or decorative noise that hurts usability.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'place_card_design',
        'label': 'Place Card Design [event] [stationery]',
        'tags': ['event', 'stationery'],
        'description': 'Place-card style with refined name emphasis, tabletop elegance, and compact readable formatting.',
        'instruction': 'Design as a place card with strong guest-name readability, clean spacing, and polished event stationery presentation. Preserve elegance and tabletop usability without overdecorating the small format.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'postcard_design',
        'label': 'Postcard Design [design] [print]',
        'tags': ['design', 'print', 'postcard', 'card'],
        'description': 'Postcard style with bold front-side focal imagery, concise messaging, and clean print-mailer composition.',
        'instruction': 'Design as a postcard with strong front-side impact, readable message hierarchy, and balanced layout suitable for print or direct mail. Preserve compact clarity, premium finish, and a clean relationship between imagery and text without poster-like overcrowding.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'price_list_design',
        'label': 'Price List / Service List [design] [business]',
        'tags': ['design', 'business', 'price-list', 'print'],
        'description': 'Clear service-list design with structured pricing hierarchy, practical readability, and business-ready layout discipline.',
        'instruction': 'Design as a professional price list or service menu with clean category grouping, strong alignment, readable typography, and fast client-facing scanability. Keep the layout functional, organized, and polished without overdecoration or unnecessary visual complexity.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'save_the_date_card',
        'label': 'Save the Date Card [design] [event]',
        'tags': ['design', 'event', 'card', 'announcement'],
        'description': 'Clean event-announcement style with memorable focal design, clear date emphasis, and polished keepsake-card readability.',
        'instruction': 'Design as a save-the-date card with strong emphasis on the date, clear names or event title, and elegant supporting layout. Preserve memorable focal styling, disciplined typography, and a print-friendly composition that feels intentional and easy to read at a glance. Keep the design uncluttered and announcement-first.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'seating_chart_sign',
        'label': 'Seating Chart Sign [event] [signage]',
        'tags': ['event', 'signage'],
        'description': 'Event seating-chart style with strong alphabetical or table hierarchy and elegant large-format readability.',
        'instruction': 'Design as a seating chart sign with clear names, table assignments, and large-format readability suitable for event display. Preserve elegant structure, fast scanning, and sign-ready spacing without overcrowding the layout.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'table_number_card',
        'label': 'Table Number Card [event] [stationery]',
        'tags': ['event', 'stationery'],
        'description': 'Table-number card style with elegant numbering hierarchy and clean event-table readability.',
        'instruction': 'Design as a table number card with strong numeral emphasis, tasteful decorative restraint, and clear readability from a short distance. Preserve event cohesion, print readiness, and balanced composition without unnecessary detail.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'thank_you_card_design',
        'label': 'Thank You Card [design] [stationery]',
        'tags': ['design', 'stationery', 'card', 'print'],
        'description': 'Polished thank-you card style with graceful typography, balanced layout, and warm premium stationery presentation.',
        'instruction': 'Design as a thank-you card with clear message focus, elegant spacing, tasteful typography, and clean print-ready composition. Preserve warmth, sincerity, and readability while keeping the design uncluttered and suitable for personal, professional, or event follow-up use.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'trifold_brochure',
        'label': 'Trifold Brochure [design] [print]',
        'tags': ['design', 'print', 'brochure', 'trifold'],
        'description': 'Trifold brochure style with panel-aware layout structure, strong scanability, and professionally organized marketing flow.',
        'instruction': 'Design as a trifold brochure with clear panel divisions, fold-conscious content planning, strong front-cover hierarchy, and readable internal information flow. Preserve spacing discipline, visual cohesion, and print-ready structure without overloading any single panel.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'wedding_rsvp',
        'label': 'Wedding Invitation / RSVP [design] [event]',
        'tags': ['design', 'event', 'invite', 'rsvp'],
        'description': 'Elegant wedding invitation style with refined typography, balanced composition, and premium event-stationery polish.',
        'instruction': 'Design as a wedding invitation or RSVP piece with elegant hierarchy, refined spacing, tasteful decorative restraint, and excellent readability. Preserve premium stationery-like presentation, clear event details, and a cohesive formal tone appropriate for print or digital invitation use. Avoid clutter, novelty graphics, or overly busy compositions that weaken the upscale feel.',
        'main_category': 'Print / Stationery / Event Materials',
    },
    {
        'key': 'wedding_program',
        'label': 'Wedding Program [event] [print]',
        'tags': ['event', 'print'],
        'description': 'Wedding-program style with elegant ceremony hierarchy, readable sequencing, and refined stationery presentation.',
        'instruction': 'Design as a wedding program with clear ceremony flow, tasteful typography, balanced spacing, and premium printed-stationery polish. Preserve readability, formal tone, and keepsake quality without decorative overload.',
        'main_category': 'Print / Stationery / Event Materials',
    },
]
