from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'chase_cam_style',
        'label': 'Chase Cam [shot-type] [camera-motion]',
        'tags': ['shot-type', 'camera-motion'],
        'description': 'Chase-camera style with kinetic pursuit framing, forward momentum, and readable movement path.',
        'instruction': 'Direct the shot as a chase-cam sequence with strong pursuit energy, subject tracking, and directional clarity. Preserve speed, urgency, and route readability without letting the camera become so chaotic that the subject or movement path is lost.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'dolly_zoom_shot',
        'label': 'Dolly Zoom Shot [shot-type] [camera-motion]',
        'tags': ['shot-type', 'camera-motion'],
        'description': 'Dolly-zoom shot style with spatial disorientation, psychological emphasis, and dramatic perspective distortion.',
        'instruction': 'Direct the shot as a dolly zoom with synchronized camera movement and focal change that distorts spatial relationships for dramatic effect. Preserve a clear emotional or psychological motivation so the effect lands as intentional rather than gimmicky.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'extreme_closeup_shot',
        'label': 'Extreme Close-Up Shot [shot-type] [cinematography]',
        'tags': ['shot-type', 'cinematography'],
        'description': 'Extreme-close-up shot style with hyper-focused visual emphasis, emotional compression, and detail-dominant framing.',
        'instruction': 'Direct the shot as an extreme close-up with very tight framing on a critical detail such as eyes, hands, lips, an object, or a meaningful texture. Preserve shallow focal hierarchy, emotional intensity, and strong visual intent so the closeness feels purposeful rather than arbitrarily cropped or unreadable.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'insert_shot_style',
        'label': 'Insert Shot [shot-type] [editing]',
        'tags': ['shot-type', 'editing'],
        'description': 'Insert-shot style with precise object emphasis, narrative clarity, and clean supplementary visual focus.',
        'instruction': 'Direct the shot as an insert focused on a meaningful object, interaction, interface, clue, or gesture that supports the main action. Preserve crisp readability, clear relevance, and tight visual discipline so the insert enhances the sequence rather than feeling like decorative filler.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'killcam_style',
        'label': 'Killcam / Finisher Cam [shot-type] [game-cinematic]',
        'tags': ['shot-type', 'game-cinematic'],
        'description': 'Killcam style with impact emphasis, dramatic angle selection, and readable event payoff.',
        'instruction': 'Direct the shot like a killcam or finisher cam with strong impact timing, clear victim-attacker relationship, and visually satisfying event emphasis. Preserve readability, motion coherence, and decisive payoff without drowning the moment in random over-effects.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'locked_off_tableau_shot',
        'label': 'Locked-Off Tableau Shot [shot-type] [cinematography]',
        'tags': ['shot-type', 'cinematography'],
        'description': 'Locked-off tableau style with static composition, choreographed in-frame action, and strong visual arrangement.',
        'instruction': 'Direct the shot as a static locked-off composition where movement happens within the frame rather than through camera motion. Preserve strong visual organization, layered blocking, and sustained readability so the shot feels deliberate and painterly instead of inert.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'medium_two_shot',
        'label': 'Medium Two-Shot [shot-type] [performance]',
        'tags': ['shot-type', 'performance'],
        'description': 'Medium two-shot style with relational blocking, shared performance space, and clean dual-subject readability.',
        'instruction': 'Direct the shot as a medium two-shot framing two subjects clearly within the same emotional and spatial field. Preserve body language interaction, relative power or intimacy, and balanced composition so both characters remain readable and connected.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'over_the_shoulder_shot',
        'label': 'Over-the-Shoulder Shot [shot-type] [cinematography]',
        'tags': ['shot-type', 'cinematography'],
        'description': 'Over-the-shoulder shot style with relational framing, conversational geography, and subject-priority focus.',
        'instruction': 'Direct the shot as an over-the-shoulder composition with clear foreground shoulder framing, readable subject emphasis, and strong conversational or confrontational geography. Preserve eye-line logic, spatial continuity, and shot readability without letting the foreground block or clutter the scene excessively.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'profile_two_shot',
        'label': 'Profile Two-Shot [shot-type] [performance]',
        'tags': ['shot-type', 'performance'],
        'description': 'Profile two-shot style with face-to-face tension, symmetrical confrontation, and strong silhouette dialogue framing.',
        'instruction': 'Direct the shot as a profile two-shot showing both subjects in side view with clear visual tension and balanced silhouette readability. Preserve emotional contrast, eye-line intensity, and clean spatial symmetry without flattening the shot into lifeless staging.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'rack_focus_shot',
        'label': 'Rack Focus Shot [shot-type] [cinematography]',
        'tags': ['shot-type', 'cinematography'],
        'description': 'Rack-focus shot style with controlled attention shift, layered depth, and clean focal transition logic.',
        'instruction': 'Direct the shot around a rack focus that shifts visual emphasis from one plane, subject, or object to another. Preserve strong depth separation, meaningful focal progression, and readable visual storytelling without making the focus pull feel arbitrary or mushy.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'reaction_shot_style',
        'label': 'Reaction Shot [shot-type] [performance]',
        'tags': ['shot-type', 'performance'],
        'description': 'Reaction-shot style with performance emphasis, emotional readability, and tightly focused narrative response.',
        'instruction': 'Direct the shot as a reaction moment centered on facial response, body language, or silent emotional processing. Preserve expression clarity, timing, and narrative relevance so the shot lands as an emotionally meaningful beat rather than an arbitrary cutaway.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'slow_push_in_shot',
        'label': 'Slow Push-In Shot [shot-type] [cinematography]',
        'tags': ['shot-type', 'cinematography'],
        'description': 'Slow push-in style with gradual emphasis, emotional tightening, and restrained dramatic build.',
        'instruction': 'Direct the shot as a slow push-in toward the subject or focal point, using subtle movement to build intimacy, tension, or significance. Preserve compositional stability and emotional clarity so the movement feels deliberate and cumulative rather than distracting.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'whip_pan_transition_shot',
        'label': 'Whip Pan Transition Shot [shot-type] [transition]',
        'tags': ['shot-type', 'transition'],
        'description': 'Whip-pan transition style with fast directional motion, energetic scene linkage, and momentum-preserving continuity.',
        'instruction': 'Use a whip-pan shot or whip-pan transition with strong directional blur, fast movement, and clear scene-to-scene momentum. Preserve intentional directionality and transition logic so the shot connects beats cleanly rather than becoming chaotic blur.',
        'main_category': 'Shot Types',
    },
    {
        'key': 'wide_establishing_shot',
        'label': 'Wide Establishing Shot [shot-type] [scene-type]',
        'tags': ['shot-type', 'scene-type'],
        'description': 'Wide-establishing shot style with location clarity, scale emphasis, and strong opening geography.',
        'instruction': 'Direct the shot as a wide establishing image with clear spatial orientation, scale cues, and immediate scene comprehension. Preserve environment readability, strong composition, and a clear sense of where the action takes place without filling the frame with irrelevant clutter.',
        'main_category': 'Shot Types',
    },
]
