from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'snow_fx_blizzard',
        'label': 'Blizzard Snow FX [sfx] [atmosphere]',
        'tags': ['sfx', 'atmosphere'],
        'description': 'Blizzard-snow effects style with wind-driven snow motion, visibility reduction, and cold environmental intensity.',
        'instruction': 'Render blizzard or heavy snow effects with directional wind, layered particle depth, atmospheric cold, and realistic visibility reduction. Preserve scene structure and emotional intensity while avoiding flat white visual mush.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'energy_burst_fx',
        'label': 'Energy Burst FX [sfx] [action]',
        'tags': ['sfx', 'action'],
        'description': 'Energy-burst effects style with impact-driven light, directional force, and clean readable power release.',
        'instruction': 'Render energy-burst effects with strong directional force, luminous intensity, shockwave logic, and readable action emphasis. Preserve impact, timing, and compositional clarity without filling the screen with uncontrolled effects clutter.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'fire_smoke_fx',
        'label': 'Fire and Smoke FX [sfx] [atmosphere]',
        'tags': ['sfx', 'atmosphere'],
        'description': 'Fire-and-smoke effects style with layered combustion behavior, readable heat motion, and cinematic atmospheric response.',
        'instruction': 'Render fire and smoke effects with convincing flame movement, smoke layering, heat-driven turbulence, and strong environmental interaction. Preserve volume, timing, and readability so the effect enhances the scene without swallowing the action in opaque chaos.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'glitch_transition_fx',
        'label': 'Glitch Transition FX [sfx] [transition]',
        'tags': ['sfx', 'transition'],
        'description': 'Glitch-transition style with digital rupture, signal instability, and stylized scene-switch impact.',
        'instruction': 'Use glitch-based transition effects with controlled digital tearing, RGB splitting, distortion pulses, or signal breaks to move between beats. Preserve visual intention, timing clarity, and transition readability so the effect feels designed rather than like random corruption.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'rain_fx_heavy',
        'label': 'Heavy Rain FX [sfx] [atmosphere]',
        'tags': ['sfx', 'atmosphere'],
        'description': 'Heavy-rain effects style with dense precipitation, surface interaction, and dramatic weather-driven visual texture.',
        'instruction': 'Render heavy rain with believable droplet density, directional fall behavior, splashes, wet-surface response, and atmosphere shaped by precipitation. Preserve visibility and mood without making the image so obscured that the scene loses its readability.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'hud_augmented_vision',
        'label': 'HUD Augmented Vision [vision-mode] [ui-motion]',
        'tags': ['vision-mode', 'ui-motion'],
        'description': 'Augmented-vision style with integrated HUD overlays, tactical readouts, and screen-driven target emphasis.',
        'instruction': 'Render the scene through an augmented-vision interface with HUD overlays, target tracking, readouts, and system-like visual support elements that feel integrated with the viewpoint. Preserve clear visual hierarchy, mode realism, and readable overlays without overwhelming the actual scene.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'infrared_surveillance_mode',
        'label': 'Infrared Surveillance Mode [vision-mode] [security]',
        'tags': ['vision-mode', 'security'],
        'description': 'Infrared surveillance style with monochrome low-light coverage, security-camera realism, and night-operations clarity.',
        'instruction': 'Render the scene as infrared surveillance footage with monochrome or IR-lit night coverage, fixed security framing, and believable low-light sensor behavior. Preserve security-camera realism and readable spatial structure without cinematic stylization.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'lightning_storm_fx',
        'label': 'Lightning Storm FX [sfx] [atmosphere]',
        'tags': ['sfx', 'atmosphere'],
        'description': 'Lightning-storm effects style with atmospheric charge, flash timing, and environment-responsive energy.',
        'instruction': 'Render lightning effects with believable flash intensity, branching energy, environmental illumination, and storm-driven visual rhythm. Preserve timing, contrast, and weather mood without making every frame equally bright or chaotic.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'night_vision_mode',
        'label': 'Night Vision Mode [vision-mode] [sfx]',
        'tags': ['vision-mode', 'sfx'],
        'description': 'Night-vision style with low-light amplification, green-tinted imaging, sensor grain, and tactical visibility logic.',
        'instruction': 'Render the scene in night-vision mode with believable low-light amplification, sensor grain, restricted contrast response, and a tactical green-toned or monochrome imaging aesthetic. Preserve visibility, device realism, and mode-specific behavior without turning the effect into a generic color filter.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'portal_activation_fx',
        'label': 'Portal Activation FX [sfx] [scifi]',
        'tags': ['sfx', 'scifi'],
        'description': 'Portal-activation style with dimensional opening effects, spatial distortion, and high-readability sci-fi energy.',
        'instruction': 'Render a portal or dimensional opening with layered energy, spatial distortion, environmental response, and a clear sense of activation progression. Preserve visual readability, scale, and cause-effect timing rather than turning the portal into a generic glowing hole.',
        'main_category': 'Special Effects / Vision Modes',
    },
    {
        'key': 'thermal_vision_mode',
        'label': 'Thermal Vision Mode [vision-mode] [sfx]',
        'tags': ['vision-mode', 'sfx'],
        'description': 'Thermal-vision style with heat-signature contrast, environmental temperature separation, and readable sensor logic.',
        'instruction': 'Render the scene in thermal vision with clear heat-based differentiation between subjects and surroundings, believable sensor interpretation, and strong temperature-based visual hierarchy. Preserve mode readability and tactical clarity rather than using decorative rainbow effects without heat logic.',
        'main_category': 'Special Effects / Vision Modes',
    },
]
