from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'assembly_instruction_sheet',
        'label': 'Assembly Instruction Sheet [technical] [instruction]',
        'tags': ['technical', 'instruction'],
        'description': 'Instruction-sheet style with step-by-step assembly logic, readable panels, and function-first technical clarity.',
        'instruction': 'Design as an assembly instruction sheet with sequential panels, clear step numbering, simple diagrams, and part or tool visibility where useful. Preserve instructional flow, fast comprehension, and uncluttered layout rather than decorative illustration.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'blueprint_technical',
        'label': 'Blueprint Technical Drawing [technical] [blueprint]',
        'tags': ['technical', 'blueprint'],
        'description': 'Technical blueprint style with measured linework, orthographic discipline, annotation-ready spacing, and engineering readability.',
        'instruction': 'Render as an engineering blueprint with precise line hierarchy, orthographic clarity, clean structural separation, and disciplined monochrome or blueprint-cyan palette. Suppress painterly rendering and prioritize measurement-ready technical communication.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'callout_annotation_diagram',
        'label': 'Callout Annotation Diagram [technical] [reference]',
        'tags': ['technical', 'reference'],
        'description': 'Annotated-diagram style with leader lines, callout hierarchy, and clean explanatory layout.',
        'instruction': 'Render as a callout annotation diagram with clearly placed labels, readable leader lines, strong spacing discipline, and uncluttered explanatory structure. Preserve diagram legibility and label-to-part relationships without decorative interference or cramped layout.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'character_silhouette_sheet',
        'label': 'Character Silhouette Sheet [character] [design-sheet]',
        'tags': ['character', 'design-sheet'],
        'description': 'Silhouette-sheet style with strong shape-language comparison, readable character differentiation, and early-design clarity.',
        'instruction': 'Render as a silhouette sheet showing multiple character or outfit silhouettes with clean spacing and strong black-shape readability. Preserve shape-language contrast, design variety, and quick-read character identity without interior-detail dependence.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'cutaway_technical_illustration',
        'label': 'Cutaway Technical Illustration [technical] [diagram]',
        'tags': ['technical', 'diagram'],
        'description': 'Cutaway technical style revealing interior structure while preserving external form clarity and educational readability.',
        'instruction': 'Render as a cutaway technical illustration with clean sectioned surfaces, visible internal components, and balanced visibility between outer shell and interior mechanisms. Preserve clear hierarchy, structural readability, and instructional usefulness rather than cinematic drama or messy transparency effects.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'diagram_schematic',
        'label': 'Diagram / Schematic [technical] [diagram]',
        'tags': ['technical', 'diagram'],
        'description': 'Clean schematic-diagram style with simplified forms, process clarity, and instructional visual hierarchy.',
        'instruction': 'Render as a technical diagram with simplified shapes, clear part separation, annotation-friendly spacing, and process-first communication. Suppress decorative rendering and prioritize explanation, legibility, and structured layout.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'embroidery_stitch_art',
        'label': 'Embroidery / Stitch Art [craft] [textile]',
        'tags': ['craft', 'textile'],
        'description': 'Thread-based embroidery style with stitched texture, tactile fabric grounding, and decorative handcrafted clarity.',
        'instruction': 'Render as embroidery or stitched textile art with visible thread paths, stitched edges, layered fabric behavior, and handcrafted decorative structure. Preserve tactile softness and pattern readability while avoiding painted or printed-surface simulation.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'exploded_view_diagram',
        'label': 'Exploded View Diagram [technical] [diagram]',
        'tags': ['technical', 'diagram'],
        'description': 'Exploded-view technical style with separated components, assembly clarity, and engineering-focused spatial readability.',
        'instruction': 'Render as an exploded-view diagram with clearly separated parts, logical assembly spacing, alignment lines where useful, and strong technical readability. Preserve part relationships, mechanical hierarchy, and instructional clarity without decorative rendering or confusing perspective distortion.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'fabric_pattern_sheet',
        'label': 'Fabric Pattern Sheet [technical] [textile]',
        'tags': ['technical', 'textile'],
        'description': 'Textile-pattern sheet style with swatch organization, print-readiness, and fabric-design review clarity.',
        'instruction': 'Design as a fabric pattern sheet with neatly organized swatches, repeat visibility, colorway comparison where useful, and clear labeling zones. Preserve textile readability, pattern consistency, and design-review practicality rather than decorative collage behavior.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'hard_surface_design_sheet',
        'label': 'Hard-Surface Design Sheet [technical] [design-sheet]',
        'tags': ['technical', 'design-sheet'],
        'description': 'Hard-surface design-sheet style with mechanical form exploration, panel logic, and production-readable layout.',
        'instruction': 'Render as a hard-surface design sheet with multiple views, callouts, silhouette exploration, and clean mechanical readability. Preserve form-function logic, material separation, and development clarity without over-rendered hero-shot styling.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'infographic_editorial',
        'label': 'Infographic Editorial [data-viz] [design]',
        'tags': ['data-viz', 'design'],
        'description': 'Editorial infographic style with structured information hierarchy, icon consistency, strong scanability, and publication-grade clarity.',
        'instruction': 'Compose as a publication-grade infographic with concise visual grouping, chart and icon consistency, strong spacing rhythm, and clear information scanning flow. Keep layout disciplined, labels readable, and decorative noise minimal so the information remains primary.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'material_swatch_reference_sheet',
        'label': 'Material Swatch Reference Sheet [technical] [reference]',
        'tags': ['technical', 'reference'],
        'description': 'Material-swatch reference style with organized sample presentation, finish differentiation, and design-review clarity.',
        'instruction': 'Design as a material swatch sheet with clearly separated samples, readable labels, consistent sample sizing, and strong visual comparison structure. Preserve finish distinction, color/material clarity, and presentation order while keeping the sheet clean and decision-friendly.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'mechanical_parts_sheet',
        'label': 'Mechanical Parts Sheet [technical] [engineering]',
        'tags': ['technical', 'engineering'],
        'description': 'Mechanical-parts sheet style with component separation, labeling readiness, and engineering-oriented visual order.',
        'instruction': 'Render as a parts sheet with clearly separated mechanical components, consistent scale logic, readable spacing, and technical presentation clarity. Preserve part identity, assembly relationships, and catalog-like cleanliness without dramatic lighting or decorative composition.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'medical_illustration',
        'label': 'Medical Illustration [medical] [technical]',
        'tags': ['medical', 'technical'],
        'description': 'Clinical illustration style balancing anatomical accuracy, educational clarity, and clean professional presentation.',
        'instruction': 'Use precise anatomical structure, simplified hierarchy, clean labeling zones, and medically legible material differentiation suitable for educational or clinical contexts. Preserve accuracy, clarity, and neutrality while avoiding sensational rendering or unnecessary visual clutter.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'orthographic_design_sheet',
        'label': 'Orthographic Design Sheet [technical] [design-sheet]',
        'tags': ['technical', 'design-sheet'],
        'description': 'Design-sheet style with front-side-back view logic, clean alignment, and development-oriented presentation.',
        'instruction': 'Render as an orthographic design sheet with aligned multiple views, consistent scale, clean spacing, and technical readability. Preserve development clarity and presentation order rather than cinematic rendering or perspective drama.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'patent_drawing_style',
        'label': 'Patent Drawing Style [technical] [linework]',
        'tags': ['technical', 'linework'],
        'description': 'Patent-drawing style with precise linework, monochrome clarity, and invention-focused technical presentation.',
        'instruction': 'Render as a patent-style drawing with clean monochrome linework, structured view labeling, consistent technical hatching or contour logic, and minimal decorative rendering. Preserve clarity, precision, and legal-document readability rather than artistic stylization.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'prop_turnaround_sheet',
        'label': 'Prop Turnaround Sheet [technical] [design-sheet]',
        'tags': ['technical', 'design-sheet'],
        'description': 'Prop-turnaround style with multi-angle object clarity, scale discipline, and asset-production readability.',
        'instruction': "Render as a prop turnaround sheet with clean isolated views, consistent scale, neutral background, and reliable structural readability. Preserve the object's shape, materials, and function cues clearly across views without mood-lighting or distracting composition.",
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'vehicle_turnaround_sheet',
        'label': 'Vehicle Turnaround Sheet [technical] [design-sheet]',
        'tags': ['technical', 'design-sheet'],
        'description': 'Vehicle-turnaround style with aligned views, proportion control, and production-ready transport-design readability.',
        'instruction': 'Render as a vehicle turnaround sheet with front, side, rear, and additional useful views aligned at consistent scale. Preserve clean silhouette continuity, wheelbase and body proportion accuracy, and technical clarity rather than cinematic presentation.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'weapon_design_sheet',
        'label': 'Weapon Design Sheet [technical] [design-sheet]',
        'tags': ['technical', 'design-sheet'],
        'description': 'Weapon-design sheet style with silhouette clarity, part logic, and development-oriented technical presentation.',
        'instruction': 'Render as a weapon design sheet with multiple views, optional component callouts, clear silhouette readability, and strong form hierarchy. Preserve believable assembly logic, scale relationships, and production usefulness without over-stylized action-poster treatment.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
    {
        'key': 'xray_imaging',
        'label': 'X-Ray Imaging [technical] [medical]',
        'tags': ['technical', 'medical'],
        'description': 'Radiographic x-ray style emphasizing internal structure visibility, density variation, technical grayscale readability, and diagnostic clarity.',
        'instruction': 'Render with x-ray visual logic: translucent outer forms, internal structural emphasis, grayscale density variation, and clean technical clarity. Suppress decorative atmosphere and keep the result clinical, legible, and function-first.',
        'main_category': 'Technical / Diagram / Medical / Reference',
    },
]
