from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'calligraphic_blackletter',
        'label': 'Blackletter / Gothic Type [text] [calligraphy]',
        'tags': ['text', 'calligraphy'],
        'description': 'Blackletter typography style with ornate historic structure, strong vertical rhythm, and dramatic formal density.',
        'instruction': 'Render text as blackletter or gothic calligraphy with disciplined stroke contrast, sharp angular rhythm, and historically inspired structure. Preserve visual richness and period flavor while maintaining enough readability and spacing control for the intended use.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'balloon_text_cartoon',
        'label': 'Cartoon Balloon Text [text] [comic]',
        'tags': ['text', 'comic'],
        'description': 'Comic balloon-text style with expressive lettering, playful outlines, and speech-bubble readability.',
        'instruction': 'Render text as cartoon or comic balloon lettering with bold outlines, playful shape language, clear interior readability, and strong small-format clarity. Preserve energy and comic-book flavor without letting distortion compromise the text.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'glass_text',
        'label': 'Glass Text [text] [material]',
        'tags': ['text', 'material'],
        'description': 'Glass-text style with translucent material behavior, refraction cues, and elegant high-clarity dimensionality.',
        'instruction': 'Render text as glass lettering with realistic transparency, refraction behavior, clean edge definition, and controlled highlight response. Preserve readability and material plausibility without overcomplicating the environment or making the glass unreadably noisy.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'graffiti_lettering',
        'label': 'Graffiti Lettering [text] [street-art]',
        'tags': ['text', 'street-art'],
        'description': 'Graffiti-lettering style with dynamic letter structure, urban energy, and expressive spray-paint character.',
        'instruction': 'Render text as graffiti lettering with bold stylized forms, aerosol texture cues, layered line energy, and strong wall-ready attitude. Preserve readability or controlled semi-readability according to the style while keeping the lettering cohesive and visually powerful.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'hand_lettered_script',
        'label': 'Hand-Lettered Script [text] [calligraphy]',
        'tags': ['text', 'calligraphy'],
        'description': 'Hand-lettered script style with flowing stroke rhythm, elegant handmade character, and premium artisanal readability.',
        'instruction': 'Render text as hand-lettered script with natural stroke taper, flowing rhythm, and graceful handcrafted movement. Preserve legibility, line quality, and spacing discipline without letting flourishes overwhelm the wording.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'kinetic_type_graphic',
        'label': 'Kinetic Type Graphic [text] [experimental]',
        'tags': ['text', 'experimental'],
        'description': 'Kinetic-type style with directional energy, motion-oriented arrangement, and expressive typographic rhythm.',
        'instruction': 'Render text as kinetic typography with directional flow, size contrast, dynamic spacing, and movement-driven composition. Preserve legibility and intentional rhythm so the motion energy feels designed rather than chaotic.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'metallic_3d_text',
        'label': 'Metallic 3D Text [text] [3d]',
        'tags': ['text', '3d'],
        'description': 'Metallic 3D text style with dimensional beveling, controlled reflections, and polished title-card presence.',
        'instruction': 'Render text as dimensional metallic lettering with believable bevels, reflective material behavior, clean edge control, and strong depth separation. Preserve readability and premium finish without excessive chrome glare or cluttered background interference.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'neon_sign_text',
        'label': 'Neon Sign Text [text] [lighting]',
        'tags': ['text', 'lighting'],
        'description': 'Neon-sign text style with glowing tubing, emissive color bloom, and realistic sign-like illumination behavior.',
        'instruction': 'Render text as a neon sign with believable tube construction, controlled glow bloom, reflective spill, and realistic illuminated-sign presence. Preserve readability, sign clarity, and lighting discipline without turning the text into an unreadable glow blob.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'paper_cut_text',
        'label': 'Paper Cut Text [text] [craft]',
        'tags': ['text', 'craft'],
        'description': 'Paper-cut text style with layered cutout depth, tactile edges, and handcrafted typographic composition.',
        'instruction': 'Render text as layered paper-cut lettering with visible cut contours, stacked depth, soft cast shadows, and handcrafted material clarity. Preserve legibility and paper-material logic without flattening the effect into generic vector text.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'ransom_note_text',
        'label': 'Ransom Note Text [text] [collage]',
        'tags': ['text', 'collage'],
        'description': 'Cut-and-paste ransom-note typography style with mismatched letterforms, collage tension, and deliberately irregular composition.',
        'instruction': 'Render text as ransom-note typography using mismatched cutout letters, varied type sources, and assembled collage-like composition. Preserve visual tension and intentional irregularity while keeping the wording readable enough for the intended use.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'retro_signage_text',
        'label': 'Retro Signage Text [text] [vintage]',
        'tags': ['text', 'vintage'],
        'description': 'Retro-signage typography style with nostalgic commercial character, period letterforms, and storefront readability.',
        'instruction': 'Render text as retro signage with era-appropriate letterforms, commercial sign structure, and strong nostalgic visual identity. Preserve readability, vintage flavor, and balanced decorative treatment without making the lettering messy or inconsistent.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'typography_bold_poster',
        'label': 'Typography Bold Poster [text] [poster]',
        'tags': ['text', 'poster'],
        'description': 'Bold poster-typography style with oversized type, strong impact, and high-distance readability.',
        'instruction': 'Render text as bold poster typography with oversized letterforms, strong contrast, clear hierarchy, and immediate graphic impact. Preserve readability and compositional force while avoiding overcrowding, poor spacing, or inconsistent type treatment.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'typography_clean_editorial',
        'label': 'Typography Clean Editorial [text] [editorial]',
        'tags': ['text', 'editorial'],
        'description': 'Editorial typography style with refined hierarchy, elegant spacing, and publication-grade text composition.',
        'instruction': 'Render text as clean editorial typography with strong hierarchy, disciplined kerning, balanced line spacing, and premium publication-style composition. Preserve legibility, elegance, and typographic restraint without decorative clutter or novelty distortion.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'typography_luxury_serif',
        'label': 'Typography Luxury Serif [text] [branding]',
        'tags': ['text', 'branding'],
        'description': 'Luxury serif typography style with premium spacing, elegant contrast, and upscale brand presentation.',
        'instruction': 'Render text in a luxury serif style with refined proportions, graceful letter spacing, and premium editorial-brand polish. Preserve sophistication, clarity, and restraint rather than ornate excess or weak hierarchy.',
        'main_category': 'Text Rendering / Typography',
    },
    {
        'key': 'typography_modern_sans',
        'label': 'Typography Modern Sans [text] [branding]',
        'tags': ['text', 'branding'],
        'description': 'Modern sans-serif typography style with clean geometry, contemporary hierarchy, and polished brand-ready readability.',
        'instruction': 'Render text in a modern sans-serif style with clean line weight, disciplined alignment, strong spacing, and clear typographic hierarchy. Preserve contemporary clarity and precision without decorative gimmicks or cluttered composition.',
        'main_category': 'Text Rendering / Typography',
    },
]
