from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'ui_app_mockup',
        'label': 'App UI Mockup [ui] [product-design]',
        'tags': ['ui', 'product-design'],
        'description': 'Modern application UI mockup with strong hierarchy, clean layout rhythm, readable components, and product-ready interface clarity.',
        'instruction': 'Design as a polished app interface with disciplined spacing, readable typography hierarchy, clear interaction states, and practical component consistency. Keep the layout product-realistic and usability-first rather than decorative or concept-noisy.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'dashboard_ui_mockup',
        'label': 'Dashboard UI Mockup [ui] [data]',
        'tags': ['ui', 'data'],
        'description': 'Data-dashboard UI style with information hierarchy, chart readability, and polished product-facing interface structure.',
        'instruction': 'Design as a professional dashboard interface with clear metric cards, readable data visualizations, organized navigation, and strong hierarchy between primary and secondary information. Preserve clarity, scanability, and product realism while avoiding decorative noise or dense unreadable chart clutter.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'device_screen_mockup',
        'label': 'Device Screen Mockup [mockup] [tech]',
        'tags': ['mockup', 'tech'],
        'description': 'Tech-device mockup style with realistic hardware framing, screen integration, and commercial product presentation.',
        'instruction': 'Render as a device screen mockup with believable device proportions, accurate screen placement, realistic reflections, and clean presentation lighting. Preserve product realism and screen readability while keeping the hardware context supportive rather than overpowering the displayed design.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'ecommerce_product_page_mockup',
        'label': 'Ecommerce Product Page Mockup [ui] [commerce]',
        'tags': ['ui', 'commerce'],
        'description': 'Ecommerce product-page style with conversion-focused hierarchy, clean merchandising structure, and shopping-flow clarity.',
        'instruction': 'Design as a professional ecommerce product page with dominant product imagery, clear pricing and CTA zones, readable feature sections, review modules, and variant-selection structure. Preserve trust-building hierarchy, retail usability, and clean page rhythm rather than cluttered marketplace chaos.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'game_ui_mockup',
        'label': 'Game UI Mockup [ui] [game]',
        'tags': ['ui', 'game'],
        'description': 'Game interface mockup style with production-aware HUD hierarchy, usable affordances, and strong readability over active backgrounds.',
        'instruction': 'Design as usable game UI with hierarchy-first typography, icon consistency, state clarity, and contrast strong enough for in-motion readability. Preserve clear interaction logic, clean grouping, and production-style interface discipline rather than decorative sci-fi noise.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'hud_overlay_design',
        'label': 'HUD Overlay Design [ui] [game]',
        'tags': ['ui', 'game'],
        'description': 'Game-HUD overlay style with gameplay readability, layered information hierarchy, and in-motion visual discipline.',
        'instruction': 'Design as a usable in-game HUD overlay with readable bars, icons, counters, notifications, and minimap or objective treatment where relevant. Preserve contrast, gameplay-first visibility, and state clarity over complex backgrounds without turning the UI into decorative sci-fi noise.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'mobile_app_screen_flow',
        'label': 'Mobile App Screen Flow [ui] [product-design]',
        'tags': ['ui', 'product-design'],
        'description': 'Mobile-screen flow style with multi-screen continuity, clean interaction logic, and app-product design readability.',
        'instruction': 'Design as a mobile app flow with multiple aligned screens showing step-by-step navigation, consistent component language, and clear interaction progression. Preserve spacing discipline, mobile-first readability, and practical UX logic rather than isolated beauty-shot screens with no functional continuity.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'product_mockup',
        'label': 'Product Mockup [mockup] [branding]',
        'tags': ['mockup', 'branding'],
        'description': 'Presentation mockup style that showcases graphics on believable products with realistic perspective, print integration, and commercial polish.',
        'instruction': 'Output as a clean commercial mockup with correct perspective, realistic print or surface integration, believable material response, and lighting that sells the final branded deliverable. Keep the product presentation clear, premium, and client-facing rather than overly stylized.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'saas_product_ui',
        'label': 'SaaS Product UI [ui] [business]',
        'tags': ['ui', 'business'],
        'description': 'Business-software UI style with clean enterprise hierarchy, practical workflows, and modern SaaS-product polish.',
        'instruction': 'Design as a polished SaaS interface with clear navigation, modular cards, tables, forms, and business-oriented information architecture. Preserve professional clarity, usability, and product realism while avoiding decorative visual overload or consumer-app novelty styling.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'stream_overlay_package',
        'label': 'Stream Overlay Package [ui] [streaming]',
        'tags': ['ui', 'streaming'],
        'description': 'Streaming-overlay package style with modular broadcast panels, readable labels, and polished creator-brand presentation.',
        'instruction': 'Design as a stream overlay package with webcam frame, alert zones, lower-thirds, chat framing, and clean brand-cohesive styling. Preserve broadcast readability, modular component consistency, and screen-safe spacing without overcrowding the live-content area.',
        'main_category': 'UI / Product / Mockups',
    },
    {
        'key': 'website_landing_page_mockup',
        'label': 'Website Landing Page Mockup [ui] [web]',
        'tags': ['ui', 'web'],
        'description': 'Modern landing-page mockup style with strong hero hierarchy, clean section flow, and product-grade web readability.',
        'instruction': 'Design as a polished website landing page with a clear hero section, structured content blocks, readable typography hierarchy, and conversion-oriented visual flow. Preserve responsive-minded spacing, strong focal messaging, and interface realism without overcrowding the page or collapsing into poster-like composition.',
        'main_category': 'UI / Product / Mockups',
    },
]
