from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'arthouse_slow_cinema',
        'label': 'Arthouse Slow Cinema [direction] [atmosphere]',
        'tags': ['direction', 'atmosphere'],
        'description': 'Slow-cinema style with long-duration composition, minimal action, and contemplative visual patience.',
        'instruction': 'Direct the scene with slow-cinema discipline using restrained movement, long-held framing, subtle blocking changes, and a deep focus on duration, silence, and observation. Preserve emotional and spatial tension through patience and composition rather than rapid edits or overt spectacle.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'chaotic_action_sequence',
        'label': 'Chaotic Action Sequence [direction] [sequence]',
        'tags': ['direction', 'sequence'],
        'description': 'High-energy action-direction style with readable impact, rapid escalation, and controlled visual chaos.',
        'instruction': 'Direct the scene as a fast-moving action sequence with strong momentum, escalating beats, and impactful visual rhythm. Preserve clarity of who is doing what, where the movement is going, and what the stakes are, using energetic but readable camera behavior, clear stunt geography, and sharp beat-to-beat progression instead of incoherent motion overload.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'cinematic_master_scene',
        'label': 'Cinematic Master Scene [direction] [cinematography]',
        'tags': ['direction', 'cinematography'],
        'description': 'Wide cinematic scene-direction style with strong blocking, readable action geography, and controlled dramatic visual flow.',
        'instruction': 'Direct the scene as a cinematic master shot with strong spatial clarity, readable subject blocking, and clear foreground-midground-background relationships. Preserve coherent action geography, deliberate staging, motivated lighting, and a stable dramatic rhythm so the viewer always understands where the subjects are, how they move, and what the scene is emphasizing over time.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'coming_of_age_memory_style',
        'label': 'Coming-of-Age Memory Style [scene-type] [atmosphere]',
        'tags': ['scene-type', 'atmosphere'],
        'description': 'Nostalgic coming-of-age style with lived-in warmth, memory-like pacing, and emotionally grounded visual storytelling.',
        'instruction': 'Direct the scene with a coming-of-age sensibility using natural environments, emotionally resonant detail, and a gentle balance between realism and memory-softened feeling. Preserve intimacy, youthfulness, and narrative clarity without drifting into sentimental cliche or visual over-sweetening.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'commercial_lifestyle_scene',
        'label': 'Commercial Lifestyle Scene [commercial] [performance]',
        'tags': ['commercial', 'performance'],
        'description': 'Lifestyle-commercial style with aspirational realism, polished interaction, and brand-safe visual warmth.',
        'instruction': 'Direct the scene as a lifestyle commercial with natural but elevated behavior, clean environment interactions, and polished human presence. Preserve aspirational realism, readable action, and positive emotional tone while keeping the product, service, or lifestyle message visually central and uncluttered.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'commercial_product_reveal',
        'label': 'Commercial Product Reveal [commercial] [direction]',
        'tags': ['commercial', 'direction'],
        'description': 'Product-reveal style with premium pacing, controlled visual emphasis, and polished commercial desirability.',
        'instruction': 'Direct the scene as a product reveal with clean pacing, escalating detail emphasis, and premium presentation polish. Preserve material appeal, brand-friendly framing, controlled motion, and reveal timing that builds desire and clarity without cluttering the sequence with unrelated distraction.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'courtroom_drama_scene',
        'label': 'Courtroom Drama Scene [direction] [performance]',
        'tags': ['direction', 'performance'],
        'description': 'Courtroom-drama style with performance tension, structured blocking, and rhetoric-driven visual focus.',
        'instruction': 'Direct the scene as courtroom drama with strong speaking turns, power-position blocking, reaction emphasis, and restrained visual control. Preserve legal-space geography, performance intensity, and rhetorical weight without making the scene visually static or theatrically exaggerated.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'crane_lift_reveal',
        'label': 'Crane Lift Reveal [camera-motion] [scene-type]',
        'tags': ['camera-motion', 'scene-type'],
        'description': 'Crane-reveal style with vertical discovery, scale emphasis, and cinematic expansion of the scene.',
        'instruction': 'Direct the scene as a crane or rising reveal with layered vertical staging, strong scale cues, and gradual disclosure of the environment or action. Preserve a clean reveal hierarchy and strong compositional payoff instead of exposing everything too early or making the movement arbitrary.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'documentary_interview_setup',
        'label': 'Documentary Interview Setup [documentary] [cinematography]',
        'tags': ['documentary', 'cinematography'],
        'description': 'Interview-direction style with grounded framing, natural performance space, and editorial clarity.',
        'instruction': 'Direct the scene as a documentary interview with composed but believable framing, controlled background context, and natural performance emphasis. Preserve eye-line consistency, subtle posture, honest expression, and lighting that feels polished yet credible rather than theatrical or overly stylized.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'documentary_observational',
        'label': 'Documentary Observational [documentary] [direction]',
        'tags': ['documentary', 'direction'],
        'description': 'Observational documentary style with natural behavior, unobtrusive camera language, and lived-in realism.',
        'instruction': 'Direct the scene as observational documentary footage with natural movement, unstaged behavior, and camera choices that feel present but not overly manipulative. Preserve authenticity, situational texture, real-time rhythm, and truthful environmental detail rather than polished commercial choreography.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'dreamlike_memory_sequence',
        'label': 'Dreamlike Memory Sequence [scene-type] [atmosphere]',
        'tags': ['scene-type', 'atmosphere'],
        'description': 'Dream-memory scene style with softened logic, emotional fragments, and poetic visual continuity.',
        'instruction': 'Direct the scene as a dreamlike or memory-based sequence with softened transitions, emotionally weighted imagery, and fluid temporal logic. Preserve coherence through recurring visual anchors, controlled surrealism, and gentle scene-to-scene flow rather than random abstract fragmentation.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'drone_establishing_sequence',
        'label': 'Drone Establishing Sequence [cinematography] [scene-type]',
        'tags': ['cinematography', 'scene-type'],
        'description': 'Drone-establishing style with location scale, broad movement clarity, and controlled environmental overview.',
        'instruction': 'Direct the scene as a drone-style establishing sequence with wide spatial awareness, smooth aerial motion, and strong location readability. Preserve geographic clarity, scale, and cinematic overview without making the shot feel like generic travel footage.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'fantasy_world_reveal',
        'label': 'Fantasy World Reveal [scene-type] [atmosphere]',
        'tags': ['scene-type', 'atmosphere'],
        'description': 'Fantasy reveal style with mythic scale, layered environment discovery, and immersive wonder-driven pacing.',
        'instruction': 'Direct the scene as a fantasy-world reveal with strong landscape hierarchy, progressive visual disclosure, and a sense of awe through scale, architecture, or atmosphere. Preserve environmental readability and emotional buildup so the reveal feels magical, coherent, and transportive.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'fashion_film_direction',
        'label': 'Fashion Film Direction [direction] [editorial]',
        'tags': ['direction', 'editorial'],
        'description': 'Fashion-film style with pose-aware movement, stylized blocking, and mood-forward editorial motion.',
        'instruction': 'Direct the scene as a fashion film with deliberate pose transitions, elegant movement, premium styling emphasis, and controlled editorial pacing. Preserve garment readability, body-line clarity, atmosphere, and visual sophistication without sacrificing motion coherence or scene continuity.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'found_footage_horror',
        'label': 'Found Footage Horror [scene-type] [documentary]',
        'tags': ['scene-type', 'documentary'],
        'description': 'Found-footage horror style with unstable immediacy, imperfect framing, and fear built through apparent realism.',
        'instruction': 'Direct the scene as found-footage horror with imperfect handheld framing, panic-driven movement, and the feeling of captured reality under stress. Preserve believable camera limitations, partial visibility, and escalating fear while keeping enough spatial coherence that the action remains understandable.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'handheld_urgency_style',
        'label': 'Handheld Urgency [camera-motion] [direction]',
        'tags': ['camera-motion', 'direction'],
        'description': 'Urgent handheld style with immediate energy, reactive framing, and controlled instability.',
        'instruction': 'Direct the scene with handheld urgency using reactive framing, slight instability, and close-to-the-action presence while preserving readability and emotional focus. Keep the movement energetic and immersive, but controlled enough that the viewer can still track performance, action, and space.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'heist_planning_scene',
        'label': 'Heist Planning Scene [direction] [scene-type]',
        'tags': ['direction', 'scene-type'],
        'description': 'Heist-planning scene style with tactical blocking, information clarity, and tension through controlled preparation.',
        'instruction': 'Direct the scene as a heist-planning sequence with readable table or wall-based staging, tactical gestures, group hierarchy, and tension built through precision rather than action. Preserve information clarity, team dynamics, and strategic visual storytelling without cluttering the frame with meaningless props or confusion.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'hero_entrance_moment',
        'label': 'Hero Entrance Moment [direction] [scene-type]',
        'tags': ['direction', 'scene-type'],
        'description': 'Hero-introduction style with deliberate buildup, strong silhouette reveal, and confident character emphasis.',
        'instruction': 'Direct the scene as a hero entrance with controlled buildup, silhouette-first readability, and strong visual emphasis on presence, attitude, and impact. Preserve a clear reveal structure, confident body language, strong composition, and timing that lets the character own the frame without rushing the moment.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'high_tension_confrontation',
        'label': 'High-Tension Confrontation [direction] [scene-type]',
        'tags': ['direction', 'scene-type'],
        'description': 'Confrontation scene style with escalating blocking, compressed tension, and controlled visual pressure.',
        'instruction': 'Direct the scene as a tense confrontation with rising spatial pressure, emotionally charged body language, and clear dramatic escalation. Preserve eye-line tension, stance changes, proximity shifts, and camera emphasis that heighten conflict while keeping the action legible and the emotional power grounded in performance rather than chaos.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'horror_corridor_scene',
        'label': 'Horror Corridor Scene [scene-type] [atmosphere]',
        'tags': ['scene-type', 'atmosphere'],
        'description': 'Horror corridor scene style with constrained space, creeping dread, and controlled environmental tension.',
        'instruction': 'Direct the scene as a horror corridor moment with narrow spatial pressure, ominous pacing, and carefully limited visual information. Preserve corridor depth, environmental unease, and tension-building camera restraint without breaking the scene with excessive monster exposure or visual chaos too early.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'intimate_dialogue_scene',
        'label': 'Intimate Dialogue Scene [direction] [performance]',
        'tags': ['direction', 'performance'],
        'description': 'Performance-led dialogue scene style with subtle blocking, emotional proximity, and restrained cinematic realism.',
        'instruction': 'Direct the scene as an intimate dialogue moment with emotionally readable blocking, subtle eye-line control, and quiet performance emphasis. Preserve natural conversational rhythm, believable pauses, restrained gestures, and camera choices that support tension, connection, or vulnerability without overpowering the acting with excessive movement or visual distraction.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'investigation_scene',
        'label': 'Investigation Scene [direction] [scene-type]',
        'tags': ['direction', 'scene-type'],
        'description': 'Investigation scene style with clue emphasis, environmental scrutiny, and measured procedural pacing.',
        'instruction': 'Direct the scene as an investigation with close attention to details, evidence, gaze direction, and environmental storytelling. Preserve a careful pace, procedural clarity, and meaningful object emphasis so the viewer understands what matters and why without losing atmosphere.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'match_cut_transition_style',
        'label': 'Match Cut Transition Style [editing] [transition]',
        'tags': ['editing', 'transition'],
        'description': 'Match-cut style with visual continuity, shape or motion echoing, and elegant transition intelligence.',
        'instruction': 'Construct the sequence using match cuts that connect scenes through shape, movement, framing, or symbolic visual relationships. Preserve seamless conceptual continuity and visual cleverness while keeping the transitions clean and readable rather than gimmicky.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'montage_editorial_rhythm',
        'label': 'Montage Editorial Rhythm [editing] [sequence]',
        'tags': ['editing', 'sequence'],
        'description': 'Editorial montage style with rhythmic cut logic, visual contrast, and progression-focused sequence structure.',
        'instruction': 'Direct the sequence through montage logic with strong beat contrast, meaningful image selection, and a clear progression arc. Preserve editorial rhythm, emotional or thematic buildup, and visual variety while ensuring the sequence still feels unified and purposeful.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'music_video_conceptual_style',
        'label': 'Music Video Conceptual [music-video] [experimental]',
        'tags': ['music-video', 'experimental'],
        'description': 'Concept-driven music-video style with symbolic imagery, visual motifs, and rhythm-shaped surreal structure.',
        'instruction': 'Direct the scene as a conceptual music-video sequence built around strong visual motifs, symbolic beats, and emotionally driven image logic. Preserve a coherent aesthetic language, repeatable thematic elements, and rhythm-aware structure so the video feels intentional, expressive, and visually memorable rather than random.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'music_video_performance_style',
        'label': 'Music Video Performance [music-video] [direction]',
        'tags': ['music-video', 'direction'],
        'description': 'Performance-forward music-video style with rhythm-aware blocking, visual attitude, and strong artist focus.',
        'instruction': 'Direct the scene as a music-video performance with strong performer presence, rhythm-sensitive movement, and visually assertive composition. Preserve charisma, stylized camera behavior, expressive lighting, and beat-aware motion while keeping the performer or focal subject dominant and visually compelling throughout.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'one_take_sequence_style',
        'label': 'One-Take Sequence [direction] [camera-motion]',
        'tags': ['direction', 'camera-motion'],
        'description': 'Continuous-shot sequence style with uninterrupted flow, blocking precision, and choreography-driven scene coherence.',
        'instruction': 'Direct the scene as a one-take sequence with seamless subject movement, precise camera choreography, and coherent transitions through space and action. Preserve the illusion of continuity, spatial geography, and performance rhythm without awkward resets, impossible jumps, or blocking confusion.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'orbital_reveal_shot',
        'label': 'Orbital Reveal Shot [camera-motion] [cinematography]',
        'tags': ['camera-motion', 'cinematography'],
        'description': 'Orbital camera-reveal style with rotational staging, progressive disclosure, and high visual payoff.',
        'instruction': 'Direct the scene around an orbital reveal with controlled circular movement, strong center-of-interest logic, and a clear reveal structure. Preserve spatial coherence, character or object emphasis, and elegant timing so the orbit enhances discovery rather than creating confusion.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'overhead_tableau_scene',
        'label': 'Overhead Tableau Scene [cinematography] [scene-type]',
        'tags': ['cinematography', 'scene-type'],
        'description': 'Overhead-tableau style with top-down clarity, choreographed composition, and graphic scene organization.',
        'instruction': 'Direct the scene from a top-down or overhead perspective with strong composition, organized movement, and clearly readable spatial relationships. Preserve design-like clarity and choreographed subject placement without losing emotional or narrative legibility.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'POV_subjective_camera',
        'label': 'POV Subjective Camera [camera-motion] [performance]',
        'tags': ['camera-motion', 'performance'],
        'description': 'Subjective POV style with first-person immersion, limited viewpoint knowledge, and experiential visual logic.',
        'instruction': "Direct the scene from a subjective point of view that feels tied to a specific character's body, awareness, and emotional state. Preserve believable head-height or body-linked motion, partial information, and experiential realism without becoming unreadably erratic.",
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'procedural_tv_style',
        'label': 'Procedural TV Style [broadcast] [scene-type]',
        'tags': ['broadcast', 'scene-type'],
        'description': 'Procedural-television style with efficient scene coverage, clue or task clarity, and broadcast-readable pacing.',
        'instruction': 'Direct the scene like procedural TV with efficient coverage, clear task or evidence emphasis, and narrative-forward pacing. Preserve clarity of information, character purpose, and location logic while avoiding visual clutter or unnecessary art-house ambiguity.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'romantic_walk_and_talk',
        'label': 'Romantic Walk-and-Talk [direction] [performance]',
        'tags': ['direction', 'performance'],
        'description': 'Walk-and-talk romance style with natural movement, conversational rhythm, and emotionally soft visual pacing.',
        'instruction': 'Direct the scene as a romantic walk-and-talk with natural body language, easy conversational cadence, and gentle spatial movement through the environment. Preserve chemistry, readable expressions, and fluid blocking without stiff staging or melodramatic excess.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'sci_fi_arrival_scene',
        'label': 'Sci-Fi Arrival Scene [scene-type] [cinematography]',
        'tags': ['scene-type', 'cinematography'],
        'description': 'Sci-fi arrival style with scale reveal, environmental awe, and controlled futuristic spectacle.',
        'instruction': 'Direct the scene as a sci-fi arrival moment with strong scale cues, environmental reveal structure, and a sense of technological or cosmic wonder. Preserve visual hierarchy, atmosphere, and believable staging so the grandeur feels earned and readable rather than like unstructured effects noise.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'slow_burn_suspense_scene',
        'label': 'Slow-Burn Suspense Scene [direction] [atmosphere]',
        'tags': ['direction', 'atmosphere'],
        'description': 'Suspense-direction style with delayed reveals, restrained pacing, and steadily mounting unease.',
        'instruction': 'Direct the scene with slow-burn suspense using controlled pacing, delayed visual information, careful blocking, and tension-building environmental detail. Preserve the feeling of anticipation through measured camera movement, silence or restrained action, subtle framing shifts, and reveal timing that gradually intensifies unease without breaking the mood too early.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'smash_cut_impact_style',
        'label': 'Smash Cut Impact Style [editing] [transition]',
        'tags': ['editing', 'transition'],
        'description': 'Smash-cut transition style with abrupt contrast, strong dramatic punctuation, and high-impact scene switching.',
        'instruction': 'Use smash cuts to create strong contrast between beats, locations, emotions, or action levels. Preserve clarity of intention and dramatic punctuation so the abruptness feels purposeful and forceful rather than random or disorienting.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'smooth_tracking_shot_style',
        'label': 'Smooth Tracking Shot [camera-motion] [cinematography]',
        'tags': ['camera-motion', 'cinematography'],
        'description': 'Smooth-tracking style with elegant subject following, spatial clarity, and premium controlled motion.',
        'instruction': 'Direct the scene with smooth tracking movement that follows the subject with precision, stable rhythm, and strong environmental continuity. Preserve grace, directionality, and composition while avoiding floaty aimlessness or overcomplicated pathing that distracts from the subject.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'sports_documentary_style',
        'label': 'Sports Documentary Style [sports] [documentary]',
        'tags': ['sports', 'documentary'],
        'description': 'Sports-documentary style with grounded realism, effort detail, and emotionally credible competitive presence.',
        'instruction': 'Direct the scene as sports documentary footage with emphasis on effort, preparation, reaction, and authentic physical presence. Preserve realism, body mechanics, sideline or environmental texture, and emotional honesty rather than glossy over-stylization.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'sports_hype_sequence',
        'label': 'Sports Hype Sequence [sequence] [sports]',
        'tags': ['sequence', 'sports'],
        'description': 'Sports-hype direction style with impact cuts, performance intensity, and momentum-driven visual storytelling.',
        'instruction': 'Direct the scene as a sports hype sequence with explosive energy, physical intensity, sharp performance beats, and strong movement clarity. Preserve athlete readability, action impact, emotional drive, and a sense of escalating momentum without devolving into unreadable blur or random highlight spam.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'teaser_minimal_mystery',
        'label': 'Teaser Minimal Mystery [trailer] [atmosphere]',
        'tags': ['trailer', 'atmosphere'],
        'description': 'Minimal teaser style with restrained information, mystery-driven pacing, and strong atmosphere-first control.',
        'instruction': 'Direct the sequence as a teaser that withholds information strategically, emphasizes mystery, and uses atmosphere, fragments, and suggestive imagery to create anticipation. Preserve intrigue and tonal consistency without overexplaining or exposing the main payoff too early.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'trailer_hype_structure',
        'label': 'Trailer Hype Structure [trailer] [editing]',
        'tags': ['trailer', 'editing'],
        'description': 'Trailer-style direction with escalating beats, reveal pacing, and high-impact promotional structure.',
        'instruction': 'Direct the sequence as a trailer with escalating reveal beats, sharp tonal pivots, high-value visual moments, and controlled hype-building structure. Preserve clarity, pacing, and anticipation so the sequence feels like a compelling campaign piece rather than a random collection of cool shots.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'training_montage_sequence',
        'label': 'Training Montage Sequence [sequence] [editing]',
        'tags': ['sequence', 'editing'],
        'description': 'Montage-direction style with progression beats, repeated motifs, and rhythmic visual momentum.',
        'instruction': 'Direct the scene as a training montage built from clear progression moments, repeated visual motifs, and rising skill or endurance cues. Preserve a strong sense of forward movement through changing locations, effort beats, physical detail, and escalating performance intensity while keeping the sequence visually varied and easy to follow.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'travel_journey_sequence',
        'label': 'Travel Journey Sequence [sequence] [atmosphere]',
        'tags': ['sequence', 'atmosphere'],
        'description': 'Journey-sequence style with passage-of-time storytelling, environmental variety, and emotional movement through space.',
        'instruction': 'Direct the scene as a travel or journey sequence with a clear sense of motion through locations, time, and mood. Preserve changing environments, transition logic, visual continuity, and a progression arc that makes the movement feel purposeful rather than like disconnected postcards.',
        'main_category': 'Video Directing / Scene Styles',
    },
    {
        'key': 'villain_reveal_scene',
        'label': 'Villain Reveal Scene [direction] [scene-type]',
        'tags': ['direction', 'scene-type'],
        'description': 'Villain-reveal style with ominous pacing, controlled concealment, and dominance-focused staging.',
        'instruction': 'Direct the scene as a villain reveal with measured concealment, intimidating composition, and progressive disclosure of power or menace. Preserve strong reveal timing, oppressive framing, deliberate movement, and visual emphasis on presence, threat, or control without resorting to random shock-cut chaos.',
        'main_category': 'Video Directing / Scene Styles',
    },
]
