from __future__ import annotations

from ..types import PromptStyle

STYLES: list[PromptStyle] = [
    {
        'key': 'sixteen_mm_documentary_style',
        'label': '16mm Documentary Style [video-format] [documentary]',
        'tags': ['video-format', 'documentary'],
        'description': '16mm documentary-film style with tactile grain, naturalistic movement, and grounded cinematic realism.',
        'instruction': 'Render as 16mm documentary film with visible grain, subtle gate weave, grounded handheld or observational movement, and naturalistic light response. Preserve tactile film character, realism, and intimacy without forcing overly glossy modern polish onto the sequence.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'thirtyfive_mm_cinematic_style',
        'label': '35mm Cinematic Style [video-format] [cinematic]',
        'tags': ['video-format', 'cinematic'],
        'description': '35mm film style with classic cinematic depth, natural grain, rich tonal latitude, and premium screen-language polish.',
        'instruction': 'Render as 35mm cinematic footage with natural film grain, strong tonal rolloff, elegant focus behavior, and classic motion-picture texture. Preserve premium theatrical readability, rich contrast, and grounded cinematic realism without overdoing vintage degradation or stylized gimmicks.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'analog_broadcast_style',
        'label': 'Analog Broadcast Style [video-format] [broadcast]',
        'tags': ['video-format', 'broadcast'],
        'description': 'Analog TV-broadcast style with signal softness, scan texture, and period television presentation character.',
        'instruction': 'Render as analog broadcast footage with slight signal softness, mild scanline texture, period-appropriate color response, and broadcast-era framing discipline. Preserve recognizable television formatting and analog transmission feel without pushing distortion so far that the footage becomes unusable.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'bodycam_style',
        'label': 'Bodycam Style [video-format] [immersive]',
        'tags': ['video-format', 'immersive'],
        'description': 'Bodycam footage style with chest- or head-mounted motion, reactive framing, and intense first-person immediacy.',
        'instruction': "Render as bodycam footage with wearer-linked movement, imperfect stabilization, practical FOV, and a strong sense of physical presence. Preserve urgency, realism, and attachment to the wearer's body rather than floating cinematic movement or artificial smoothing.",
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'crt_monitor_playback_style',
        'label': 'CRT Monitor Playback [video-format] [retro-tech]',
        'tags': ['video-format', 'retro-tech'],
        'description': 'CRT-monitor playback style with phosphor glow, scanline structure, curvature, and retro display signal behavior.',
        'instruction': 'Render as video viewed through a CRT monitor with phosphor bloom, scanlines, slight screen curvature, and subtle refresh or signal texture. Preserve screen-view realism and retro electronic character without destroying on-screen readability.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'dashcam_style',
        'label': 'Dashcam Style [video-format] [vehicle]',
        'tags': ['video-format', 'vehicle'],
        'description': 'Dashcam style with fixed vehicular framing, road-forward composition, and recorded-driving realism.',
        'instruction': 'Render as dashcam footage with fixed windshield-mounted perspective, practical road visibility, ambient vehicle vibration, and real-world driving composition. Preserve the believable feel of onboard recorded footage rather than cinematic chase-camera behavior.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'hi8_home_video_style',
        'label': 'Hi8 / Home Video Style [video-format] [retro-tech]',
        'tags': ['video-format', 'retro-tech'],
        'description': 'Late-90s to early-2000s home-video style with consumer-camera realism, practical lighting, and memory-like immediacy.',
        'instruction': 'Render as consumer home-video footage with modest dynamic range, handheld family-camera motion, direct practical lighting, and believable casual framing. Preserve candid realism, nostalgic imperfection, and domestic recorded-life texture without excessive degradation that destroys legibility.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'mini_dv_documentary_style',
        'label': 'MiniDV Documentary Style [video-format] [documentary]',
        'tags': ['video-format', 'documentary'],
        'description': 'MiniDV documentary style with compact-camera realism, practical exposure, and early-digital field-footage character.',
        'instruction': 'Render as MiniDV documentary footage with slightly compressed digital texture, practical location lighting, handheld responsiveness, and a grounded observational feel. Preserve field-recorded authenticity and documentary immediacy without synthetic over-grading or fake cinematic polish.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'screenlife_capture_style',
        'label': 'Screenlife Capture Style [video-format] [digital]',
        'tags': ['video-format', 'digital'],
        'description': 'Screenlife style with UI-native framing, cursor-driven activity, and digitally mediated narrative presentation.',
        'instruction': 'Render as screenlife footage with authentic on-screen interface behavior, cursor interactions, window management, alerts, and digital communication framing. Preserve the logic of real software environments and believable screen activity instead of generic floating UI abstraction.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'super8_memory_style',
        'label': 'Super 8 Memory Style [video-format] [nostalgic]',
        'tags': ['video-format', 'nostalgic'],
        'description': 'Super-8 style with grainy analog warmth, flicker, nostalgic softness, and memory-driven visual charm.',
        'instruction': 'Render as Super 8 footage with organic grain, flicker, slight gate instability, warm nostalgic color response, and imperfect analog softness. Preserve the intimate memory-film feel and emotional warmth without making the footage too damaged or unreadably distressed.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'surveillance_camera_style',
        'label': 'Surveillance Camera Style [video-format] [security]',
        'tags': ['video-format', 'security'],
        'description': 'Security-camera style with fixed framing, utilitarian coverage, and institutional observational detachment.',
        'instruction': 'Render as surveillance footage with fixed or minimally motorized framing, practical overhead or low-quality lighting, utilitarian composition, and a detached observational feel. Preserve coverage realism, time-stamped or system-like framing where appropriate, and clear security-camera behavior without overly cinematic embellishment.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'tiktok_reel_native_style',
        'label': 'TikTok / Reel Native Style [video-format] [social]',
        'tags': ['video-format', 'social'],
        'description': 'Social-native short-form style with vertical pacing, strong hook framing, and immediate on-screen readability.',
        'instruction': 'Direct the video like native short-form social content with quick attention capture, mobile-first framing, visually immediate pacing, and strong readability in the first moments. Preserve platform-native energy without reducing the sequence to chaotic overstimulation.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'ugc_creator_style',
        'label': 'UGC Creator Style [video-format] [social]',
        'tags': ['video-format', 'social'],
        'description': 'UGC creator-video style with direct-to-camera authenticity, platform familiarity, and lightly polished casual realism.',
        'instruction': 'Render as user-generated creator content with natural direct address, smartphone realism, practical lighting, and casual but intentional framing. Preserve relatability, audience-facing authenticity, and creator-style pacing rather than polished studio-commercial stiffness.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'vertical_phone_video_style',
        'label': 'Vertical Phone Video Style [video-format] [mobile]',
        'tags': ['video-format', 'mobile'],
        'description': 'Phone-native vertical-video style with handheld realism, social immediacy, and portrait-format composition.',
        'instruction': 'Render as vertical phone video with portrait framing, mobile-camera exposure logic, handheld imperfection, and subject placement that works naturally in vertical composition. Preserve smartphone realism and social-native immediacy rather than forcing horizontal cinema language into the frame.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
    {
        'key': 'vhs_camcorder_style',
        'label': 'VHS Camcorder Style [video-format] [retro-tech]',
        'tags': ['video-format', 'retro-tech'],
        'description': 'Analog VHS-camcorder style with tape softness, tracking instability, color bleed, and home-video immediacy.',
        'instruction': 'Render as VHS camcorder footage with soft analog resolution, tape noise, tracking drift, color bleed, scan imperfections, timestamp-era texture where appropriate, and imperfect handheld framing. Preserve the nostalgic recorded-on-tape feeling and analog instability without turning the image into unreadable static or random artifact overload.',
        'main_category': 'Video Format / Capture / Era Styles',
    },
]
