# 🎤 TTS Instruction Mode Definitions
# Applies to: GZ_TextToSpeech

"""
Text-to-Speech instruction modes for optimizing text for voice synthesis.
These modes transform raw text into TTS-optimized scripts with proper pacing,
pronunciation guidance, and speech-appropriate structure.
"""

TTS_MODES = {
    "Off": "",  # No preset, use custom instructions only

    "🎤 Voiceover Script": """Transform the provided text into a clean, professional voiceover script optimized for text-to-speech synthesis. Structure sentences for natural breathing rhythm using strategic punctuation: use commas for brief pauses (0.3s), periods for full stops (0.5s), and em-dashes for dramatic emphasis pauses. Keep sentences between 10-20 words for optimal pacing. Eliminate visual references ('as you can see', 'shown here') since TTS has no visual context. Replace abbreviations with spoken forms (e.g., 'Dr.' becomes 'Doctor', 'vs.' becomes 'versus'). Spell out numbers under 100 as words. Use simple, direct sentence structures—avoid nested clauses that create awkward prosody. Remove filler words, redundancies, and parenthetical asides that break speech flow. Ensure proper noun emphasis by placing important words at sentence beginnings or after natural pauses. End with clear resolution, not trailing thoughts. The script should sound authoritative yet approachable when read aloud. Provide only the final prompt.""",

    "🎤 Character Voice": """Transform the provided text into expressive character dialogue optimized for text-to-speech performance. Embed emotional cues directly into the text structure rather than relying on stage directions. Use punctuation to convey personality: exclamation marks for enthusiasm or alarm, ellipses for hesitation or trailing thoughts, question marks with exclamations for incredulity. Vary sentence length rhythmically—short, punchy sentences for tension; longer, flowing sentences for calm or contemplation. Include natural speech patterns like contractions ('don't', 'we'll'), interjections ('well', 'oh', 'hmm'), and sentence fragments for realism. For emphasis, use italics sparingly (written as *word*) or CAPS for shouting—but limit these as TTS may not interpret formatting. Write phonetically for unusual pronunciations where needed (e.g., 'gonna' instead of 'going to' for casual speech). Build emotional arcs within passages: let excitement build through increasingly shorter sentences, or convey sadness through longer, comma-heavy constructions. Remove any visual action descriptions—only include spoken words. Ensure the voice feels consistent and distinct. Provide only the final prompt.""",

    "🎤 Audiobook Narration": """Transform the provided text into polished audiobook-style narration optimized for extended listening and text-to-speech synthesis. Structure content into natural paragraphs of 3-5 sentences maximum for comfortable pacing. Insert clear paragraph breaks with double line spacing to signal chapter-like transitions. Use em-dashes and semicolons to create sophisticated sentence rhythm without fragmenting meaning. Write attributions clearly: 'he said' or 'she replied' should follow dialogue directly to avoid listener confusion. Spell out all numbers, dates, and measurements completely ('nineteen eighty-four', 'three hundred miles', 'twenty-five degrees'). Replace visual formatting (bullet points, headers, tables) with spoken transitions ('First...', 'Next...', 'Finally...'). Maintain consistent narrative tense throughout. For quoted speech within narration, frame it clearly: 'She said, quote, Hello there, end quote' or simply use natural attribution. Avoid homographs without context (clarify 'read' as 'red' or 'reed' via sentence structure). Include brief pauses before important revelations using phrases like 'And then—' or 'What she discovered was this:'. Keep vocabulary accessible but varied to maintain listener engagement across long passages. Provide only the final prompt.""",

    "🎤 Podcast Intro": """Transform the provided text into an engaging, conversational podcast introduction optimized for text-to-speech delivery. Write in first-person or direct address ('you') to create intimacy with the listener. Use casual, energetic language with natural contractions ('you're gonna love', 'we've got', 'let's dive into'). Structure the intro in three clear beats: hook (grab attention in the first sentence), context (what the episode covers), and call-to-action or transition. Keep total length under 100 words for punchy delivery. Use rhetorical questions to engage listeners: 'Ever wondered why...?' or 'What if I told you...?'. Punctuate for enthusiasm—exclamation marks energize, but limit to 2-3 per intro. Include natural verbal cues like 'So,', 'Now,', 'Alright,' to signal transitions. Spell out any podcast-specific terms or proper nouns phonetically if pronunciation is ambiguous. Avoid jargon unless immediately explained. End with forward momentum: 'Let's get into it' or 'Here's what you need to know.' Remove any timestamps, links, or visual references. The tone should feel like a friend sharing something exciting, not a formal announcement. Provide only the final prompt.""",

    "🎤 Commercial Spot": """Transform the provided text into punchy, persuasive advertising copy optimized for text-to-speech delivery in 15-60 second commercial format. Open with an immediate hook—a bold claim, provocative question, or relatable problem statement. Structure in three acts: Problem (create urgency), Solution (introduce product/service), and Action (clear call-to-action). Use short, powerful sentences averaging 5-10 words. Create rhythm through parallel structure: 'Faster setup. Better results. Lower cost.' Include one memorable tagline or slogan that sounds natural when spoken. Write numbers as words for prices under 100 ('just twenty-nine ninety-nine'), but use 'hundred' and 'thousand' for larger figures. Emphasize key benefits by placing them after brief pauses—use periods or em-dashes before important claims. Avoid complex product specifications; focus on emotional benefits and outcomes. Include urgency language: 'today', 'now', 'limited time'. Spell out brand names phonetically if pronunciation is unusual. End with crystal-clear action: 'Visit example dot com' or 'Call now at one eight hundred...' (numbers fully written). Keep energy high through active verbs and present tense. Total word count should match target spot length: ~40 words for 15 seconds, ~150 words for 60 seconds. Provide only the final prompt.""",

    "🎤 Dramatic Reading": """Transform the provided text into theatrical, emotionally resonant prose optimized for dramatic text-to-speech performance. Structure sentences with deliberate pacing for maximum impact: short sentences create tension, long flowing sentences build atmosphere. Use punctuation as a performance tool—em-dashes for sudden revelations, ellipses for suspenseful trailing, semicolons for connected but weighted thoughts. Build to climactic moments using ascending sentence intensity, then release with a single powerful short statement. Employ sensory language heavily: sounds, textures, temperatures, and visceral physical sensations translate better to audio than visual descriptions. Create contrast through juxtaposition: 'The silence was deafening. Then—chaos.' Use repetition for emphasis: 'She waited. And waited. And waited still.' Write phonetically for archaic or dramatic pronunciations where appropriate ('ne'er', 'e'en', or character-specific dialects). Avoid parenthetical asides that break dramatic momentum. For heightened moments, use fragments and single-word sentences: 'Gone.', 'Never.', 'This.' Remove all stage directions or visual cues—emotion must live in the words themselves. Vary paragraph length dramatically: single-sentence paragraphs for impact, flowing paragraphs for immersion. The text should feel like it demands to be performed, not merely read. Provide only the final prompt.""",

    "🎤 Tutorial Narration": """Transform the provided text into clear, methodical instructional narration optimized for text-to-speech delivery in educational or how-to content. Structure information in explicit sequential steps using verbal numbering: 'Step one:', 'Next,', 'Then,', 'Finally,'. Keep each instruction to one action per sentence—never combine multiple steps. Use the imperative mood for direct instructions: 'Click the button', 'Open the file', 'Select the option'. Pace complex information with strategic pauses: insert 'Now,' or 'At this point,' before important steps. Spell out all technical terms, acronyms, and abbreviations on first use ('API, which stands for Application Programming Interface'). Use consistent terminology—never switch between synonyms mid-tutorial ('click' vs 'press' vs 'tap'). Provide audio-only spatial references: 'the option at the top of the list' rather than 'the blue button on the left'. Include brief confirmations between steps: 'Once you see the confirmation message, you'll know it worked.' Warn before critical actions: 'Important: before the next step, make sure you've saved your work.' Estimate times verbally: 'This will take about thirty seconds.' Avoid visual references entirely—describe what the listener should hear, feel (haptic), or understand instead. End each section with a brief summary. Total pacing should allow listeners to follow along in real-time. Provide only the final prompt.""",

    "🎤 SSML Enhancement": """Transform the provided text into Speech Synthesis Markup Language (SSML) enhanced format for precise text-to-speech control. Wrap the entire output in <speak> tags. Use <break time='300ms'/> for short pauses, <break time='500ms'/> for medium pauses, and <break time='1s'/> for dramatic pauses. Apply <emphasis level='strong'> for important words and <emphasis level='moderate'> for secondary stress. Use <prosody rate='slow'> for deliberate sections and <prosody rate='fast'> for energetic passages. Control pitch with <prosody pitch='high'> for excitement or <prosody pitch='low'> for gravity. For numbers, use <say-as interpret-as='cardinal'> for counting, <say-as interpret-as='ordinal'> for rankings, and <say-as interpret-as='telephone'> for phone numbers. Spell difficult words phonetically using <phoneme alphabet='ipa'> or <sub alias='spoken form'>written form</sub> for abbreviations. Use <p> for paragraph breaks and <s> for sentence boundaries where natural flow requires explicit marking. Apply <amazon:breath/> or natural pause patterns before long passages. For dates, use <say-as interpret-as='date' format='mdy'>. For currency, use <say-as interpret-as='currency'>. Note: not all TTS engines support full SSML—use widely-compatible tags. Structure output as valid XML with properly closed tags. Include fallback plain text in comments for unsupported engines. Provide only the final prompt.""",
}

TEXT_TO_AUDIO_MODES = {
    "Off": "",

    "🔊 Audio Prompt Enhance": """You are an expert text-to-audio prompt enhancer. Rewrite the user's text into a stronger, generation-ready audio prompt while preserving intent and tone. Clarify what should be heard first, the primary sound focus, environment or ambience, emotional direction, and sonic texture. If the request implies music, include useful musical cues such as genre, tempo feel, instrumentation, and energy arc. If it implies non-musical audio, include voice character, pacing, clarity, and atmosphere cues. Keep the output concise, specific, and directly usable for audio generation. Do not include explanations or meta commentary. Provide only the final prompt.""",

    "🔊 Music Direction": """Transform the user's idea into a clear music-generation brief. Preserve the core concept and define practical musical control cues: style/genre, tempo feel, rhythmic character, key mood, instrumentation layers, arrangement progression, and mix focus. Keep it coherent and actionable without jargon overload. Prefer concrete audible outcomes over abstract adjectives. Do not add unrelated story elements. Provide only the final prompt.""",

    "🔊 Ambience and Foley": """Transform the user's text into a layered ambience/foley prompt suitable for environmental audio generation. Specify foreground, midground, and background sound layers; movement or distance cues; texture and space characteristics; and how the soundscape evolves over time. Keep the scene physically readable and avoid contradictory audio behavior. Focus on what should be heard, in what order, and with what intensity. Provide only the final prompt.""",
}

SPEECH_TO_TEXT_MODES = {
    "Off": "",

    "🧾 Clean Transcript": """Rewrite transcript text for readability while preserving the original meaning, named entities, and factual content. Remove filler words when they do not add meaning, fix obvious grammar issues, and improve sentence boundaries and punctuation. Keep tone neutral and faithful to the source. Do not invent facts. Provide only the cleaned transcript.""",

    "🧾 Punctuation and Casing": """Restore punctuation, capitalization, and sentence structure for raw ASR text while preserving original wording and meaning. Keep edits minimal and faithful. Do not summarize or paraphrase unless the source is clearly malformed and requires light smoothing for readability. Provide only the corrected transcript.""",

    "🧾 Structured Notes": """Convert transcript text into concise, high-signal notes while preserving key facts, decisions, action items, and important names. Keep the output clear and practical. Avoid speculative additions. If details are missing, do not fabricate. Provide only the final notes.""",
}

TTS_MODE_NAMES = list(TTS_MODES.keys())
TEXT_TO_AUDIO_MODE_NAMES = list(TEXT_TO_AUDIO_MODES.keys())
SPEECH_TO_TEXT_MODE_NAMES = list(SPEECH_TO_TEXT_MODES.keys())

def get_tts_mode(mode_name: str) -> str:
    """Get the instruction prompt for a TTS mode."""
    return TTS_MODES.get(mode_name, "")


def get_text_to_audio_mode(mode_name: str) -> str:
    """Get the instruction prompt for a text-to-audio mode."""
    return TEXT_TO_AUDIO_MODES.get(mode_name, "")


def get_speech_to_text_mode(mode_name: str) -> str:
    """Get the instruction prompt for a speech-to-text mode."""
    return SPEECH_TO_TEXT_MODES.get(mode_name, "")
